// 32 Organization/Admin Topics (National Standards Governance, DPIIT QCO Audits, GeM Categorization, CVC Compliance)
export const ADMIN_TOPICS = [
  {
    name: 'National Standardization Compliance Audit: Public LED Street Lighting Tenders',
    category: 'National Standards Governance',
    quantity: 'National Review (450 Municipal Tenders)',
    file: 'DPIIT-AUDIT-2026-01-NATIONAL-LED-QCO.pdf',
    std: 'IS 10322 (Part 5/Sec 3): 2012',
    stdTitle: 'Luminaires - Particular Requirements - Section 3: Luminaires for Road and Street Lighting',
    edition: '3rd Revision',
    secondary: 'IS 15885 (Part 2/Sec 13): 2012',
    secondaryTitle: 'Safety of Lamp Controlgear - Electronic Controlgear for LED Modules',
    testing: 'IS 16107 (Part 2/Sec 1): 2012',
    testingTitle: 'LED Luminaires Performance Testing',
    qco: 'DPIIT Quality Control Order on Lighting & MeitY CRS Registration',
    gap: 'Nationwide sweep revealed 38% of urban local body tenders failed to mandate BIS CRS R-numbers for LED drivers.',
    remedy: 'Issue central advisory mandating automated GeM filter rejecting lighting tenders lacking IS 10322 and IS 15885.',
    spec: 'Comprehensive national audit of municipal street lighting procurement tenders examining compliance with Bureau of Indian Standards safety norms, MeitY compulsory registration, and BEE star rating parameters.'
  },
  {
    name: 'DPIIT Mandatory QCO Enforcement: Domestic Steel Products Conformance Audit',
    category: 'Statutory QCO Surveillance',
    quantity: 'National Steel Mill & Stockyard Surveillance',
    file: 'MINISTRY-STEEL-2026-02-STEEL-QCO-AUDIT.pdf',
    std: 'IS 1786: 2008 (Reaffirmed 2023)',
    stdTitle: 'High Strength Deformed Steel Bars and Wires for Concrete Reinforcement',
    edition: '4th Revision',
    secondary: 'IS 2062: 2011',
    secondaryTitle: 'Hot Rolled Medium and High Tensile Structural Steel',
    testing: 'IS 1608: 2018',
    testingTitle: 'Metallic Materials - Tensile Testing',
    qco: 'Ministry of Steel (Steel and Steel Products Quality Control Order)',
    gap: 'Unlicensed secondary re-rolling mills supplying non-ISI marked TMT rebars lacking boron and phosphorus micro-alloy control.',
    remedy: 'Enforce mandatory BIS Certification Scheme-I license verification prior to milestone payment release in all public works.',
    spec: 'Inter-ministerial surveillance report auditing adherence to Steel Quality Control Orders across state infrastructure projects, verifying heat numbers, chemical chemistry limits, and genuine ISI embossing on TMT bars.'
  },
  {
    name: 'GeM Public Procurement Portal: Low-Voltage Cable Category Harmonization Audit',
    category: 'E-Marketplace Harmonization',
    quantity: 'Systemic Platform Catalog Audit (12,000 Products)',
    file: 'GEM-STANDARDS-2026-03-CABLE-HARMONIZATION.pdf',
    std: 'IS 694: 2010',
    stdTitle: 'Polyvinyl Chloride Insulated Unsheathed and Sheathed Cables/Cords with Rigid and Flexible Conductor',
    edition: '4th Revision',
    secondary: 'IS 1554 (Part 1): 1988',
    secondaryTitle: 'PVC Insulated (Heavy Duty) Electric Cables',
    testing: 'IS 7098 (Part 1): 1988',
    testingTitle: 'XLPE Insulated Electric Cables for Working Voltages up to and including 1100 V',
    qco: 'DPIIT Electric Cables (Quality Control) Order',
    gap: 'Catalogue misalignment allowing vendors to list copper-clad aluminium (CCA) wires under pure electrolytic copper categories.',
    remedy: 'Implement automated Anveshak validation API blocking non-compliant conductor specifications on GeM portal.',
    spec: 'Harmonization framework aligning GeM product category parameters with latest BIS revisions, requiring conductor resistance verification conforming to IS 8130 and flame-retardancy classification under IS 694.'
  },
  {
    name: 'Cross-Ministry Harmonization: Potable Water Supply Pipe Selection Standards',
    category: 'Inter-Departmental Standards Policy',
    quantity: 'Inter-Departmental Review (14 States)',
    file: 'BIS-WATER-PIPE-2026-04-HARMONIZATION-AUDIT.pdf',
    std: 'IS 4984: 2016',
    stdTitle: 'Polyethylene Pipes for Water Supply - Specification',
    edition: '5th Revision',
    secondary: 'IS 8329: 2000',
    secondaryTitle: 'Centrifugally Cast (Ductile) Iron Pressure Pipes for Water, Gas and Sewage',
    testing: 'IS 1239 (Part 1): 2004',
    testingTitle: 'Steel Tubes for Water Services',
    qco: 'National Jal Jeevan Mission Technical Committee Mandate',
    gap: 'Discrepancies in soil corrosivity evaluation leading to premature failure of uncoated metallic pipes in saline belts.',
    remedy: 'Codify unified piping selection matrix linking soil electrical resistivity to mandatory pipeline metallurgy standards.',
    spec: 'National technical harmonization whitepaper establishing rigorous engineering selection guidelines between Ductile Iron (IS 8329), HDPE PE-100 (IS 4984), and mild steel pipes across rural and urban water supply schemes.'
  },
  {
    name: 'Bureau of Indian Standards National Quality Audit: Distribution Transformers',
    category: 'Regulatory Surveillance & Enforcement',
    quantity: '120 Transformer Manufacturers Audited',
    file: 'BIS-SURVEILLANCE-2026-05-TRANSFORMER-AUDIT.pdf',
    std: 'IS 1180 (Part 1): 2014',
    stdTitle: 'Outdoor Type Oil Immersed Distribution Transformers up to and including 2500 kVA, 33 kV - Specification',
    edition: '4th Revision',
    secondary: 'IS 2026: 2011',
    secondaryTitle: 'Power Transformers',
    testing: 'IS 335: 2018',
    testingTitle: 'Uninhibited Mineral Insulating Oils',
    qco: 'DPIIT Transformers Quality Control Order',
    gap: 'Random factory sampling found 22% of units exceeding maximum total losses at 50% load specified in BEE Star Level 2.',
    remedy: 'Suspend non-compliant manufacturer licenses and mandate real-time calorimetric loss testing at accredited BIS labs.',
    spec: 'Special nationwide regulatory surveillance report on distribution transformer manufacturing quality, verifying CRGO core steel grade, total losses at 50% and 100% loading, and dielectric breakdown voltage of transformer oil.'
  },
  {
    name: 'Central Vigilance Commission Procurement Gap Audit: Public Works Cement Tenders',
    category: 'Vigilance & Procurement Integrity',
    quantity: '280 Central & State PWD Tenders Evaluated',
    file: 'CVC-CEMENT-2026-06-VIGILANCE-GAP-AUDIT.pdf',
    std: 'IS 1489 (Part 1): 2015',
    stdTitle: 'Portland Pozzolana Cement - Specification - Part 1: Fly Ash Based',
    edition: '3rd Revision',
    secondary: 'IS 269: 2015',
    secondaryTitle: 'Ordinary Portland Cement',
    testing: 'IS 4031 (Parts 1-15)',
    testingTitle: 'Methods of Physical Tests for Hydraulic Cement',
    qco: 'DPIIT Cement Quality Control Order / CVC Guidelines',
    gap: 'Restrictive tender conditions favoring specific brand names over equivalent BIS-certified manufacturers.',
    remedy: 'Issue circular prohibiting restrictive proprietary branding and mandating performance-based IS standard specifications.',
    spec: 'Central Vigilance Commission technical audit identifying restrictive tender conditions, obsolete standard citations (IS 8112 / IS 12269), and establishing transparency benchmarks for cement procurement in public works.'
  },
  {
    name: 'Compulsory Registration Scheme (CRS) Electronics Regulatory Conformance Audit',
    category: 'Electronics Standards Surveillance',
    quantity: '350 IT & Consumer Electronics SKUs Tested',
    file: 'MEITY-CRS-2026-07-REGULATORY-SURVEILLANCE.pdf',
    std: 'IS 13252 (Part 1): 2010',
    stdTitle: 'Information Technology Equipment - Safety - General Requirements',
    edition: '2nd Revision',
    secondary: 'IS 16046 (Part 2): 2018',
    secondaryTitle: 'Safety Requirements for Secondary Lithium Cells',
    testing: 'IS 16333 (Part 3): 2022',
    testingTitle: 'Language Support for Mobile Handsets',
    qco: 'Ministry of Electronics & IT (MeitY) Compulsory Registration Scheme Orders',
    gap: 'Unregistered imported power adapters and sub-standard lithium batteries entering govt supply chains.',
    remedy: 'Deploy automated optical barcode / QR scanning integrated with BIS CRS database at port customs and GeM gate.',
    spec: 'Surveillance audit inspecting commercial IT equipment, laptops, interactive flat panels, and power adapters supplied to government institutions to ensure valid active R-numbers and critical safety component declarations.'
  },
  {
    name: 'National Standards Testing Laboratory NABL ISO/IEC 17025 Modernization Audit',
    category: 'Laboratory Accreditation & Metrology',
    quantity: '45 Testing Laboratories Inspected',
    file: 'BIS-LABS-2026-08-NABL-CAPABILITY-AUDIT.pdf',
    std: 'IS/ISO/IEC 17025: 2017',
    stdTitle: 'General Requirements for the Competence of Testing and Calibration Laboratories',
    edition: '2nd Revision',
    secondary: 'IS/ISO/IEC 17043: 2010',
    secondaryTitle: 'Conformity Assessment - General Requirements for Proficiency Testing',
    testing: 'IS 1608: 2018',
    testingTitle: 'Tensile Testing Calibration Standards',
    qco: 'National Accreditation Board for Testing and Calibration Laboratories (NABL) Directives',
    gap: 'Inadequate calibration traceability and lack of inter-laboratory proficiency testing in secondary testing labs.',
    remedy: 'Mandate digital unalterable test report generation (QR encoded) and direct integration with BIS Manakonline portal.',
    spec: 'Comprehensive infrastructure assessment of national testing laboratories evaluating measurement uncertainty calculations, equipment metrological traceability, automated test data logging, and proficiency testing compliance.'
  },
  {
    name: 'Fire Protection Infrastructure Compliance Audit in Central Govt High-Rises',
    category: 'Life Safety & Urban Regulations',
    quantity: '60 Central Government High-Rise Buildings',
    file: 'MHA-FIRE-2026-09-HIGHRISE-SAFETY-AUDIT.pdf',
    std: 'IS 15683: 2018',
    stdTitle: 'Portable Fire Extinguishers - Performance and Construction - Specification',
    edition: '2nd Revision',
    secondary: 'IS 2189: 2008',
    secondaryTitle: 'Selection, Installation and Maintenance of Automatic Fire Detection and Alarm System',
    testing: 'IS 3844: 1989',
    testingTitle: 'Installation and Maintenance of Internal Fire Hydrants and Hose Reels',
    qco: 'National Building Code of India (NBC 2016 Part 4 Fire and Life Safety)',
    gap: 'Overdue hydrostatic pressure stretch testing on fire extinguisher cylinders and non-functional compartmentalization fire dampers.',
    remedy: 'Institute mandatory quarterly digital fire audit logging and automated maintenance triggers linked to BIS standards.',
    spec: 'Nationwide fire safety compliance audit of central government multi-storey office secretariats evaluating automatic sprinkler coverage, fire pump room pressure maintenance, staircase pressurization, and emergency exit lighting.'
  },
  {
    name: 'Mandatory Toy Safety QCO Market Surveillance & Test Sampling Report',
    category: 'Consumer Product Safety',
    quantity: '2,500 Toy Samples Tested',
    file: 'DPIIT-TOY-2026-10-QCO-SURVEILLANCE.pdf',
    std: 'IS 9873 (Part 1): 2019',
    stdTitle: 'Safety of Toys - Part 1: Mechanical and Physical Properties',
    edition: '2nd Revision',
    secondary: 'IS 9873 (Part 2): 2017',
    secondaryTitle: 'Safety of Toys - Flammability',
    testing: 'IS 9873 (Part 3): 2020',
    testingTitle: 'Safety of Toys - Migration of Certain Elements',
    qco: 'DPIIT Toys (Quality Control) Order, 2020',
    gap: 'Counterfeit ISI markings on imported plastic toys containing high phthalate plasticizers and toxic heavy metals.',
    remedy: 'Conduct coordinated market seizures, cancel non-compliant CM/L licenses, and enforce microscopic security hologram tagging.',
    spec: 'Annual national market surveillance report assessing child toy safety under DPIIT Quality Control Order, evaluating mechanical drop test shock resistance, small parts choking hazards, phthalate plasticizer limits, and chemical safety.'
  },
  {
    name: 'National Solar Inverter & Photovoltaic Quality Control Compliance Survey',
    category: 'Renewable Standards Policy',
    quantity: '85 Solar EPC Projects Evaluated',
    file: 'MNRE-SOLAR-2026-11-QCO-COMPLIANCE-SURVEY.pdf',
    std: 'IS 14286: 2010 / IEC 61215',
    stdTitle: 'Crystalline Silicon Terrestrial Photovoltaic (PV) Modules - Design Qualification and Type Approval',
    edition: '2nd Revision',
    secondary: 'IS 16221 (Part 2): 2015',
    secondaryTitle: 'Safety Qualification of Photovoltaic Modules',
    testing: 'IS 16169: 2014',
    testingTitle: 'Anti-Islanding Protection of Utility-Interconnected Inverters',
    qco: 'MNRE Solar Photovoltaics (Quality Control) Order',
    gap: 'Sub-standard imported solar PV cells being assembled and passed off as domestic content under ALMM exemptions.',
    remedy: 'Mandate molecular forensic wafer testing and strict barcode tracing tied to MNRE approved manufacturing lines.',
    spec: 'Comprehensive quality audit of utility-scale and distributed rooftop solar installations verifying module design qualification, damp-heat degradation testing, potential-induced degradation (PID), and grid-tie inverter safety.'
  },
  {
    name: 'Railway Safety Commission Track Fasteners & Prestressed Sleepers Audit',
    category: 'Railway Infrastructure Safety',
    quantity: '4,000 Kilometers Track Section Inspected',
    file: 'CRS-RAIL-2026-12-TRACK-FASTENERS-AUDIT.pdf',
    std: 'IS 1877: 1999',
    stdTitle: 'Terminology for Iron and Steel - General and Technical Supply Conditions',
    edition: '3rd Revision',
    secondary: 'IRS T-12 / RDSO/T-3901',
    secondaryTitle: 'Elastic Rail Clips (ERC-Mk V) for Heavy Haul Tracks',
    testing: 'IRS T-46: 2020',
    testingTitle: 'Prestressed Concrete Sleepers for Broad Gauge',
    qco: 'Commission of Railway Safety (CRS) Statutory Guidelines',
    gap: 'Toe load degradation in spring steel elastic clips leading to gauge widening and track vibration risks.',
    remedy: 'Enforce silicon-manganese spring steel Grade 55Si7 conforming to IS 3195 with toe load proof testing (1040-1200 kg).',
    spec: 'Technical safety audit evaluating elastic rail clips (ERC), grooved rubber sole plates, and mono-block pre-stressed concrete sleepers across high-density freight and passenger corridors to ensure zero track fatigue defects.'
  },
  {
    name: 'Public EV Charging Station Interoperability & Electrical Grounding Protocol Audit',
    category: 'E-Mobility Standards Governance',
    quantity: '400 Public EV Charging Hubs',
    file: 'DHI-EV-2026-13-INTEROPERABILITY-AUDIT.pdf',
    std: 'IS 17017 (Part 1): 2018',
    stdTitle: 'Electric Vehicle Conductive Charging System - General Requirements',
    edition: '1st Revision',
    secondary: 'IS 3043: 2018',
    secondaryTitle: 'Code of Practice for Earthing',
    testing: 'IS 17017 (Part 23): 2021',
    testingTitle: 'DC Electric Vehicle Charging Station Requirements',
    qco: 'Central Electricity Authority (Technical Standards for Connectivity) Regulations',
    gap: 'Earth electrode resistance exceeding 5 ohms at 18% of inspected charging plazas, creating electric shock hazards.',
    remedy: 'Enforce continuous earth monitoring loop with automatic interlock disconnecting supply if ground resistance exceeds 1 ohm.',
    spec: 'National safety and operational audit of commercial EV charging plazas assessing communication handshake protocols, residual current device sensitivity, emergency stop function, and earthing bonding conforming to IS 3043.'
  },
  {
    name: 'National Smart Metering Deployment Cyber Security & Data Privacy Audit',
    category: 'Smart Grid & Cyber Security',
    quantity: '2.5 Million Smart Meter Installations Audited',
    file: 'POWER-SMARTMETER-2026-14-CYBER-SECURITY-AUDIT.pdf',
    std: 'IS 16444 (Part 1): 2015',
    stdTitle: 'A.C. Static Direct Connected Watt-Hour Smart Meters',
    edition: '1st Revision',
    secondary: 'IS 15959 (Part 2): 2016',
    secondaryTitle: 'Data Exchange for Meter Reading, Tariff and Load Control',
    testing: 'IS 13779: 1999',
    testingTitle: 'Static Watt-Hour Meters Testing Methods',
    qco: 'Ministry of Power Smart Metering Cyber Security Guidelines (CEA Norms)',
    gap: 'Default firmware keys and unencrypted over-the-air (OTA) firmware upgrade protocols identified in certain AMI networks.',
    remedy: 'Mandate AES-128 GCM encryption and asymmetric PKI mutual authentication under IS 15959 before field commissioning.',
    spec: 'Comprehensive cybersecurity audit of Advanced Metering Infrastructure (AMI) evaluating data concentrator units, Head-End Systems (HES), meter data encryption, and tamper detection logging under IS 16444.'
  },
  {
    name: 'Medical Oxygen Equipment & Cryogenic Regulators Statutory Conformance Audit',
    category: 'Biomedical Equipment Standards',
    quantity: '1,200 Medical Gas Installations Audited',
    file: 'HEALTH-O2-2026-15-OXYGEN-EQUIPMENT-AUDIT.pdf',
    std: 'IS 15001: 2002',
    stdTitle: 'Medical Gas Pipeline Systems - Specification',
    edition: '1st Revision',
    secondary: 'IS 7285: 2017',
    secondaryTitle: 'Refillable Seamless Steel Gas Cylinders',
    testing: 'ISO 10524-1',
    testingTitle: 'Pressure Regulators for Use with Medical Gases',
    qco: 'Medical Devices Rules / PESO Gas Cylinder Regulations',
    gap: 'Uncalibrated mechanical pressure relief valves on cryogenic liquid medical oxygen (LMO) vaporizers.',
    remedy: 'Require dual relief safety valves with NABL annual calibration certificates and spark-free bronze construction.',
    spec: 'Hospital medical gas safety audit assessing high-pressure cryogenic vacuum insulated storage vessels, automatic manifold switchovers, line pressure drop alarms, and emergency oxygen supply terminals.'
  },
  {
    name: 'Highway Pavement Performance & Polymer-Modified Bitumen Quality Adherence',
    category: 'Road Infrastructure Quality',
    quantity: '3,200 Lane-Kilometers Highway Audited',
    file: 'MORTH-PAVEMENT-2026-16-POLYMER-BITUMEN-AUDIT.pdf',
    std: 'IS 73: 2018',
    stdTitle: 'Paving Bitumen - Specification',
    edition: '4th Revision',
    secondary: 'IS 15462: 2019',
    secondaryTitle: 'Polymer and Rubber Modified Bitumen - Specification',
    testing: 'IS 1201 to IS 1220: 1978',
    testingTitle: 'Methods of Testing Bituminous Materials',
    qco: 'Ministry of Road Transport and Highways (MoRTH) Section 500 Specifications',
    gap: 'Premature rutting caused by blending recycled waste tyre crumb rubber exceeding permissible 15% elastomeric modifier limits.',
    remedy: 'Enforce dynamic shear rheometer (DSR) rutting parameter (G*/sin delta) and elastic recovery tests under IS 15462.',
    spec: 'National pavement engineering audit evaluating high-traffic expressway wearing courses, testing viscosity grading, softening point, Marshall stability, and resistance to moisture-induced stripping in accordance with IS 73 & IS 15462.'
  },
  {
    name: 'Defense Procurement Verification: Soldier Personal Protective Equipment',
    category: 'Defense Standards & Ballistics',
    quantity: '50,000 Soldier Protection Ensembles',
    file: 'MOD-DEFENSE-2026-17-BALLISTIC-PPE-AUDIT.pdf',
    std: 'IS 17051: 2018',
    stdTitle: 'Bullet Resistant Jackets - Specification',
    edition: '1st Revision',
    secondary: 'IS 2925: 1984',
    secondaryTitle: 'Industrial Safety Helmets Specification',
    testing: 'IS 15844: 2010',
    testingTitle: 'Leather and Combat Safety Footwear',
    qco: 'Ministry of Defense Directorate General of Quality Assurance (DGQA) Directives',
    gap: 'Back face signature (BFS trauma indentation > 25mm) exceeding safe biological threshold during 7.62x39mm ball ammunition trials.',
    remedy: 'Mandate strict compliance with IS 17051 Threat Level 5 with maximum allowable back face signature <= 20mm.',
    spec: 'Technical audit of military body armour and combat helmets inspecting boron carbide ceramic composite plates, ultra-high molecular weight polyethylene (UHMWPE) backing, trauma attenuation pads, and environmental extreme conditioning.'
  },
  {
    name: 'Footwear & Leather Products Mandatory Quality Control Order Conformance',
    category: 'Consumer Goods Standards',
    quantity: '1,500 Footwear SKUs Tested',
    file: 'DPIIT-FOOTWEAR-2026-18-QCO-CONFORMANCE-AUDIT.pdf',
    std: 'IS 15844 (Part 1): 2023',
    stdTitle: 'Leather Safety Footwear with Direct Moulded Sole - Specification',
    edition: '2nd Revision',
    secondary: 'IS 15844 (Part 2): 2023',
    secondaryTitle: 'Leather Safety Footwear with Polyurethane Sole',
    testing: 'IS 15844 (Part 3): 2023',
    testingTitle: 'Personal Protective Equipment - Footwear - Methods of Test',
    qco: 'DPIIT Footwear (Quality Control) Order, 2020',
    gap: 'Steel toe cap impact resistance (< 200 Joules) and upper leather tear strength failing below mandatory thresholds.',
    remedy: 'Mandate ISI mark under IS 15844: 2023 and reject non-compliant import consignments at major maritime ports.',
    spec: 'Surveillance report on safety and casual footwear manufacturing, inspecting impact resistance of protective toe caps, sole bond peel strength, slip resistance on ceramic tile with NaLS, and absence of carcinogenic azo dyes.'
  },
  {
    name: 'Municipal Solid Waste Incinerators & Flue Gas Air Emission Conformance',
    category: 'Environmental Pollution Control',
    quantity: '22 Waste-to-Energy Plants Audited',
    file: 'CPCB-WASTE-2026-19-EMISSION-CONFORMANCE.pdf',
    std: 'IS 12402: 1988',
    stdTitle: 'Industrial Separation and Incineration Standards',
    edition: '1st Revision',
    secondary: 'IS 5182 (Part 2): 2001',
    secondaryTitle: 'Methods for Measurement of Air Pollution - Sulphur Dioxide',
    testing: 'IS 5182 (Part 6): 2006',
    testingTitle: 'Methods for Measurement of Air Pollution - Nitrogen Oxides',
    qco: 'Central Pollution Control Board (CPCB) Solid Waste Management Rules 2016',
    gap: 'Dioxins and furans sampling (< 0.1 ng TEQ/Nm3) and continuous emission monitoring system (CEMS) sensor drift.',
    remedy: 'Enforce activated carbon injection systems and continuous telemetry transmission directly to the CPCB server.',
    spec: 'Environmental performance audit of thermal municipal waste-to-energy facilities evaluating combustion chamber temperature (>= 850 deg C), particulate matter baghouse filters, acid gas lime scrubbers, and heavy metal emissions.'
  },
  {
    name: 'Continuous Ambient Air Quality Monitoring Stations (CAAQMS) Sensor Calibration',
    category: 'Environmental Metrology',
    quantity: '180 Ambient Monitoring Stations Audited',
    file: 'CPCB-CAAQMS-2026-20-CALIBRATION-AUDIT.pdf',
    std: 'IS 5182 (Parts 1-22)',
    stdTitle: 'Methods for Measurement of Air Pollution (PM2.5, PM10, SO2, NOx, CO, O3)',
    edition: '2nd Revision',
    secondary: 'IS 13252: 2010',
    secondaryTitle: 'Information Technology Safety Standards',
    testing: 'USEPA Designated Reference and Equivalent Methods',
    testingTitle: 'Automated Equivalent Methods for Ambient Air Quality Measurement',
    qco: 'National Clean Air Programme (NCAP) Guidelines',
    gap: 'Span gas drift calibration neglected; Beta Attenuation Monitor (BAM) tape advancement jamming unrecorded.',
    remedy: 'Mandate bi-weekly zero/span automated calibration with NIST/NPL traceable gas standards under IS 5182.',
    spec: 'Metrological audit of continuous ambient air monitoring stations verifying Beta Attenuation particulate monitors, UV fluorescence SO2 analysers, chemiluminescence NOx detectors, and gas chromatography VOC analysers.'
  },
  {
    name: 'Heavy Earthmoving Machinery Roll-Over & Falling Object Protection Safety Audit',
    category: 'Industrial Machinery Safety',
    quantity: '450 Hydraulic Excavators & Wheel Loaders',
    file: 'DPIIT-MACHINERY-2026-21-ROPS-FOPS-AUDIT.pdf',
    std: 'IS 14756: 2017 / ISO 3471',
    stdTitle: 'Earth-Moving Machinery - Roll-Over Protective Structures (ROPS) - Laboratory Tests and Performance Requirements',
    edition: '1st Revision',
    secondary: 'IS 16806: 2018 / ISO 3449',
    secondaryTitle: 'Earth-Moving Machinery - Falling-Object Protective Structures (FOPS)',
    testing: 'ISO 2867 / ISO 5010',
    testingTitle: 'Earth-Moving Machinery - Access Systems and Rubber-Tyred Machines Steering Requirements',
    qco: 'DPIIT Heavy Machinery Safety Directive / Central Motor Vehicles Rules (CMVR)',
    gap: 'Tender failed to mandate ISO 3471 destructive deflection load testing for operator protective safety cabins.',
    remedy: 'Enforce structural ROPS/FOPS certified operator cabs on all heavy civil engineering equipment.',
    spec: 'Occupational safety audit inspecting hydraulic excavators, backhoe loaders, and motor graders used on public infrastructure projects to verify structural operator roll-over cab integrity, seat-belt interlocks, and emergency hydraulic dumps.'
  },
  {
    name: 'Structural Concrete Batching Plant Certification & Test Consistency Audit',
    category: 'Ready-Mixed Concrete Governance',
    quantity: '110 Commercial RMC Batching Plants',
    file: 'CPWD-RMC-2026-22-BATCHING-PLANT-SURVEILLANCE.pdf',
    std: 'IS 4926: 2003 (Reaffirmed 2019)',
    stdTitle: 'Ready-Mixed Concrete - Code of Practice',
    edition: '2nd Revision',
    secondary: 'IS 456: 2000',
    secondaryTitle: 'Plain and Reinforced Concrete Code of Practice',
    testing: 'IS 516 (Part 1/Sec 1): 2021',
    testingTitle: 'Compressive Strength of Concrete Tests',
    qco: 'Quality Council of India (QCI) Ready Mixed Concrete Plant Certification Scheme',
    gap: 'Aggregate moisture sensor automated water-cement ratio compensation bypassed during monsoon operations.',
    remedy: 'Mandate QCI RMCPC plant certification and real-time electronic batch printout archiving directly to project portals.',
    spec: 'Quality surveillance audit across commercial ready-mixed concrete plants evaluating digital load-cell calibration accuracy (conforming to IS 4926 Clause 7), fly ash blending consistency, chemical admixture dosing, and standard 28-day cube strength variance.'
  },
  {
    name: 'Telecommunications Tower Wind Load & Structural Fasteners Quality Audit',
    category: 'Telecom Infrastructure Governance',
    quantity: '1,400 Ground-Based & Rooftop Towers Audited',
    file: 'DOT-TELECOM-2026-23-TOWER-STRUCTURAL-AUDIT.pdf',
    std: 'IS 802: 1995',
    stdTitle: 'Use of Structural Steel in Overhead Towers',
    edition: '3rd Revision',
    secondary: 'IS 875 (Part 3): 2015',
    secondaryTitle: 'Design Loads (Other Than Earthquake) for Buildings and Structures - Part 3: Wind Loads',
    testing: 'IS 1367 (Parts 1-20)',
    testingTitle: 'Technical Supply Conditions for Threaded Steel Fasteners',
    qco: 'Department of Telecommunications (DoT) Infrastructure Standards',
    gap: 'Towers designed using obsolete 1987 basic wind speed maps failing to account for cyclonic wind gusts (50 m/s).',
    remedy: 'Mandate structural re-engineering compliant with IS 875 (Part 3): 2015 cyclonic risk factor (k4 = 1.30).',
    spec: 'Structural engineering audit inspecting self-supporting 4-legged lattice telecommunication towers, evaluating gust wind load calculations, hot-dip galvanizing coating thickness, foundation hold-down bolts, and antenna loading safety margins.'
  },
  {
    name: 'BIS Gold & Silver Hallmarking Center XRF Assay Accuracy Evaluation',
    category: 'Precious Metals Metrology',
    quantity: '85 Assaying and Hallmarking Centers Audited',
    file: 'BIS-HALLMARKING-2026-24-ASSAY-ACCURACY-AUDIT.pdf',
    std: 'IS 1417: 2019',
    stdTitle: 'Gold and Gold Alloys, Jewellery/Artefacts - Fineness and Marking - Specification',
    edition: '4th Revision',
    secondary: 'IS 1418: 2009',
    secondaryTitle: 'Assaying of Gold in Gold Bullion, Gold Jewellery and Gold Alloys - Cupellation (Fire Assay) Method',
    testing: 'IS 2112: 2014',
    testingTitle: 'Silver and Silver Alloys, Jewellery/Artefacts - Fineness and Marking',
    qco: 'Department of Consumer Affairs Mandatory Hallmarking of Gold Jewellery Order',
    gap: 'X-Ray Fluorescence (XRF) non-destructive assay accuracy drift exceeding +/- 0.5 parts per thousand.',
    remedy: 'Mandate mandatory destructive fire-assay (cupellation) confirmation test under IS 1418 for certified reference batches.',
    spec: 'National metrological audit evaluating BIS-recognized Assaying and Hallmarking Centers (AHCs), inspecting XRF spectrometer accuracy, micro-laser hallmarking inscription resolution, HUID digital ledger sync, and chemical cupellation furnaces.'
  },
  {
    name: 'Green Public Procurement: Eco-Mark Product Categorization & Registry Audit',
    category: 'Sustainable Procurement Policy',
    quantity: 'National Eco-Mark Standards Framework',
    file: 'MOEFCC-ECOMARK-2026-25-SUSTAINABLE-PROCUREMENT.pdf',
    std: 'IS/ISO 14024: 1999',
    stdTitle: 'Environmental Labels and Declarations - Type I Environmental Labelling - Principles and Procedures',
    edition: '1st Revision',
    secondary: 'IS/ISO 14040: 2006',
    secondaryTitle: 'Environmental Management - Life Cycle Assessment',
    testing: 'IS 17088: 2021',
    testingTitle: 'Compostable Plastics Standards',
    qco: 'Ministry of Environment, Forest and Climate Change (MoEFCC) Eco-Mark Notification 2023',
    gap: 'Absence of standardized carbon footprint and life-cycle assessment (LCA) disclosure in public procurement tenders.',
    remedy: 'Incorporate certified Eco-Mark criteria into GeM preferential procurement ranking for sustainable products.',
    spec: 'Strategic policy audit establishing comprehensive Eco-Mark environmental benchmarks for building materials, architectural coatings, paper products, and cleaning detergents conforming to IS/ISO 14024 Type I environmental labelling.'
  },
  {
    name: 'Central Public Procurement Portal (CPPP) Obsolete Standard Citation Sweep',
    category: 'Procurement Regulatory Sanitization',
    quantity: '85,000 Live Public Tender Notices Analyzed',
    file: 'DOE-CPPP-2026-26-OBSOLETE-STANDARDS-SWEEP.pdf',
    std: 'IS 456: 2000',
    stdTitle: 'Plain and Reinforced Concrete - Code of Practice',
    edition: '4th Revision',
    secondary: 'IS 800: 2007',
    secondaryTitle: 'General Construction in Steel - Code of Practice',
    testing: 'IS 13920: 2016',
    testingTitle: 'Ductile Design and Detailing of Reinforced Concrete Structures Subjected to Seismic Forces',
    qco: 'Department of Expenditure (DoE) Public Procurement Policy Manual',
    gap: 'Identification of 14,200 active government tenders citing withdrawn, superseded, or non-existent Indian Standard numbers.',
    remedy: 'Deploy Anveshak AI Copilot automated ingestion pipeline across CPPP to flag outdated standards prior to tender publication.',
    spec: 'Big data algorithmic audit scanning public procurement tenders across Central Public Procurement Portal (CPPP) and GeM, detecting obsolete citations such as IS 800: 1984 (Working Stress Method) and IS 1786: 1985.'
  },
  {
    name: 'Jal Jeevan Mission Rural Point-of-Use Water Filter Efficacy Verification',
    category: 'Public Health Standards Enforcement',
    quantity: '25,000 Community Filtration Units Evaluated',
    file: 'JALSHAKTI-2026-27-WATER-FILTER-AUDIT.pdf',
    std: 'IS 10500: 2012 (Amended 2021)',
    stdTitle: 'Drinking Water - Specification (Second Revision)',
    edition: '2nd Revision',
    secondary: 'IS 16240: 2015',
    secondaryTitle: 'Reverse Osmosis Based Point-of-Use Water Treatment Systems',
    testing: 'IS 13028: 1991',
    testingTitle: 'Gravity Based Drinking Water Treatment Systems - Specification',
    qco: 'Department of Drinking Water & Sanitation (DDWS) Mandatory Water Quality Protocols',
    gap: 'Community arsenic and fluoride removal media failing after 6 months due to backwashing neglect.',
    remedy: 'Enforce activated alumina / nano-composite media conforming to IS 10500 with automated differential pressure sensors.',
    spec: 'Field efficacy surveillance assessing point-of-use and community gravity and solar-powered water filtration plants across high-fluoride and heavy metal affected districts, verifying compliance with acceptable limits of IS 10500.'
  },
  {
    name: 'Plywood & Structural Flush Door Mandatory Quality Control Order Audit',
    category: 'Wood & Timber Products Governance',
    quantity: '450 Plywood Manufacturing Facilities Audited',
    file: 'DPIIT-PLYWOOD-2026-28-QCO-SURVEILLANCE.pdf',
    std: 'IS 303: 1989 (Reaffirmed 2020)',
    stdTitle: 'Plywood for General Purposes - Specification',
    edition: '3rd Revision',
    secondary: 'IS 2202 (Part 1): 1999',
    secondaryTitle: 'Wooden Flush Door Shutters (Solid Core Type)',
    testing: 'IS 1734 (Parts 1-20)',
    testingTitle: 'Methods of Test for Plywood',
    qco: 'DPIIT Wood Based Boards (Quality Control) Order, 2023',
    gap: 'Commercial moisture-resistant (MR) grade plywood fraudulently labeled as Boiling Water Proof (BWP IS 710).',
    remedy: 'Enforce 72-hour boiling water immersion adhesive bond test and formaldehyde emission Class E1 certification.',
    spec: 'National surveillance audit inspecting wood veneer manufacturing, assessing boiling water resistance, mycological test for fungal resistance, formaldehyde emissions, and mandatory BIS ISI stamp marking under IS 303 and IS 710.'
  },
  {
    name: 'Liquefied Petroleum Gas (LPG) Domestic Cylinders & Compact Regulators Audit',
    category: 'Consumer Gas Safety',
    quantity: '5,000 LPG Cylinders & 1,200 Regulators Sampled',
    file: 'PESO-LPG-2026-29-CYLINDER-SAFETY-AUDIT.pdf',
    std: 'IS 3196 (Part 1): 2013',
    stdTitle: 'Manufacture of Low Carbon Steel Cylinders for Low Pressure Liquefiable Gases',
    edition: '5th Revision',
    secondary: 'IS 9798: 1995',
    secondaryTitle: 'Low Pressure Regulators for Use with Liquefied Petroleum Gas (LPG) Mixtures',
    testing: 'IS 3224: 2002',
    testingTitle: 'Valve Fittings for Compressed Gas Cylinders',
    qco: 'Petroleum and Explosives Safety Organization (PESO) Gas Cylinder Rules 2016',
    gap: 'Fatigue cracks around welded foot-ring and neck collar joint in sub-standard re-conditioned cylinders.',
    remedy: 'Mandate periodic hydro-testing every 5 years, pneumatic leak test at 1.0 MPa, and barcoded traceability under IS 3196.',
    spec: 'National safety and statutory compliance audit inspecting 14.2 kg domestic LPG cylinders, evaluating low-carbon micro-alloy steel sheet quality (IS 6240), circumferential submerged arc weld radiography, and burst pressure testing (>= 8.0 MPa).'
  },
  {
    name: 'Agricultural Knapsack Power Sprayers & Nozzles Quality Conformance Audit',
    category: 'Agritech Equipment Governance',
    quantity: '850 Power Sprayers Inspected',
    file: 'AGRI-SPRAYER-2026-30-QCO-AUDIT.pdf',
    std: 'IS 3652: 1995 (Reaffirmed 2021)',
    stdTitle: 'Foot Sprayer for Agricultural Purposes - Specification',
    edition: '4th Revision',
    secondary: 'IS 10134: 1982',
    secondaryTitle: 'Method of Test for Manually Operated Sprayers',
    testing: 'IS 11313: 2007',
    testingTitle: 'Hydraulic Power Sprayers - Specification',
    qco: 'DPIIT Agricultural Machinery Quality Control Order',
    gap: 'Sub-standard brass discharge nozzles exhibiting rapid abrasive wear and non-uniform droplet spray spectrum.',
    remedy: 'Require hardened stainless steel or ceramic orifice nozzles conforming to IS 3652 discharge uniformity standards.',
    spec: 'Quality control audit of agricultural power sprayers and mist blowers inspecting high-pressure plunger pumps, chemical-resistant fluoroelastomer seals, spray boom pressure drop, and operator chemical drift protection.'
  },
  {
    name: 'Commercial Building Elevator Safety & Earthquake Counterweight Audit',
    category: 'Vertical Transportation Governance',
    quantity: '2,200 Elevators Inspected Across 8 Metros',
    file: 'URBAN-LIFT-2026-31-ELEVATOR-SAFETY-AUDIT.pdf',
    std: 'IS 14665 (Parts 1-5): 2000',
    stdTitle: 'Electric Traction Lifts - Code of Practice and Safety Requirements',
    edition: '1st Revision',
    secondary: 'IS 15785: 2007',
    secondaryTitle: 'Code of Practice for Installation and Maintenance of Lift without Machine Room',
    testing: 'IS 14665 (Part 3/Sec 1)',
    testingTitle: 'Safety Gear and Governors for Lifts',
    qco: 'State Lift Acts / Central Electricity Authority Safety Rules',
    gap: 'Absence of seismic derailment counterweight retainer brackets and bidirectional overspeed governor certification.',
    remedy: 'Mandate progressive safety gear, overspeed governor testing at 115% rated speed, and annual fitness licensing.',
    spec: 'Public safety audit inspecting passenger and freight traction lifts in government complexes, evaluating progressive safety gear tripping, electro-mechanical brake holding power, car apron dimensions, and fire-fighter recall switch operation.'
  },
  {
    name: 'Critical Healthcare Cleanrooms & Air Sterility HEPA Conformance Audit',
    category: 'Biomedical Facility Standards',
    quantity: '180 Modular Operation Theatres & Cleanrooms',
    file: 'ICMR-CLEANROOM-2026-32-STERILITY-AUDIT.pdf',
    std: 'IS 14644 (Parts 1-3) / ISO 14644-1: 2015',
    stdTitle: 'Cleanrooms and Associated Controlled Environments - Part 1: Classification of Air Cleanliness by Particle Concentration',
    edition: '2nd Revision',
    secondary: 'IS 659: 1964',
    secondaryTitle: 'Safety Code for Mechanical Refrigeration',
    testing: 'IEST-RP-CC001',
    testingTitle: 'HEPA and ULPA Filters Testing Protocols',
    qco: 'National Accreditation Board for Hospitals & Healthcare Providers (NABH) Guidelines',
    gap: 'Airborne particle count exceeding ISO Class 5 limits due to HEPA filter seal bypass leakage (PAO aerosol leak > 0.01%).',
    remedy: 'Mandate semi-annual poly-alpha-olefin (PAO) dispersed oil aerosol filter integrity testing as per IS 14644 Part 3.',
    spec: 'Sterility and airborne particulate audit of critical hospital surgical suites and pharmaceutical laboratories evaluating laminar air flow ceiling velocity (0.45 +/- 0.1 m/s), positive room pressure differential (>= 15 Pa), and HEPA filter H14 integrity.'
  }
];

console.log(`Loaded ${ADMIN_TOPICS.length} Organization/Admin topics.`);
