// 32 Government Department Topics
export const DEPT_TOPICS = [
  {
    name: 'Smart City City-Wide Surveillance AI CCTV Network & Central VMS',
    category: 'Information Technology & Surveillance',
    quantity: '1,800 IP Cameras & Central Command System',
    file: 'MOHUA-SMARTCITY-2026-01-CCTV-SURVEILLANCE.pdf',
    std: 'IS 13252 (Part 1): 2010',
    stdTitle: 'Information Technology Equipment - Safety - General Requirements',
    edition: '2nd Revision',
    secondary: 'IS/IEC 60839 (Part 11/Sec 1): 2013',
    secondaryTitle: 'Alarm and Electronic Security Systems - Video Surveillance Systems',
    testing: 'IS/IEC 60529: 2001',
    testingTitle: 'Degrees of Protection Provided by Enclosures (IP66/IK10)',
    qco: 'MeitY Compulsory Registration Scheme (CRS) & Trusted Telecom/IT Directive',
    gap: 'Tender missing mandatory cyber-security firmware hardening certification and OWASP Top 10 compliance audit.',
    remedy: 'Mandate MeitY CRS R-Number registration under IS 13252 and ONVIF Profile S/G/T conformance.',
    spec: 'City-wide AI-enabled IP video surveillance infrastructure with 4K PTZ and 5MP varifocal bullet cameras (IP67, IK10 vandal-resistant) with edge analytics, H.265+ compression, and central unified video management software.'
  },
  {
    name: 'Hospital On-Site 500 LPM Pressure Swing Adsorption (PSA) Medical Oxygen Plant',
    category: 'Healthcare Infrastructure',
    quantity: '2 Turnkey Plants (500 LPM each)',
    file: 'HEALTH-PSA-2026-02-MEDICAL-OXYGEN.pdf',
    std: 'IS 15001: 2002 (Reaffirmed 2021)',
    stdTitle: 'Medical Gas Pipeline Systems - Specification',
    edition: '1st Revision',
    secondary: 'IS 7285 (Part 2): 2017',
    secondaryTitle: 'Seamless Steel Gas Cylinders for Permanent Gases',
    testing: 'IS 10500 / Indian Pharmacopoeia (IP)',
    testingTitle: 'Medical Grade Oxygen Purity Standards (93% +/- 3%)',
    qco: 'Central Drugs Standard Control Organization (CDSCO) Medical Device Rules',
    gap: 'Carbon monoxide (<= 5 ppm) and carbon dioxide (<= 300 ppm) continuous analytical sensor monitoring omitted.',
    remedy: 'Enforce real-time zirconia oxygen purity analyser (93% +/- 3%) with automatic changeover to emergency manifold.',
    spec: 'Turnkey 500 Litres Per Minute PSA medical oxygen generation system producing 93% +/- 3% purity oxygen at 4.5 bar line pressure with oil-free air compressor, dual adsorption towers with synthetic zeolite molecular sieve, and duplex booster skid.'
  },
  {
    name: 'Govt School Ergonomic Dual Desks & Steel Storage Furniture',
    category: 'Institutional Furniture',
    quantity: '15,000 Classroom Desks',
    file: 'EDU-FURNITURE-2026-03-SCHOOL-DESKS.pdf',
    std: 'IS 4837: 1990 (Reaffirmed 2021)',
    stdTitle: 'School Furniture - Class-room Chairs and Tables - Recommendations',
    edition: '2nd Revision',
    secondary: 'IS 3845: 1966',
    secondaryTitle: 'Code of Practice for Joints Used in Wooden Furniture',
    testing: 'IS 3663: 1981',
    testingTitle: 'Specification for Drawers (Wooden)',
    qco: 'DPIIT Wooden Furniture and Steel Furniture Quality Control Orders',
    gap: 'Edge-banding adhesion test and lead-free non-toxic epoxy powder coating certification omitted.',
    remedy: 'Mandate child-safe rounded edges conforming to IS 4837 anthropometric dimensions and lead-free powder coating.',
    spec: 'Dual student classroom bench and desk units with ERW hollow square steel frame (conforming to IS 4923), 18mm pre-laminated high-density particle board (IS 3087) with 2mm machine-glued PVC edge banding.'
  },
  {
    name: '12-Meter Low-Floor Fully Electric Air-Conditioned City Transit Buses',
    category: 'Urban Mass Mobility',
    quantity: '150 Electric Buses',
    file: 'MOHUA-TRANSIT-2026-04-ELECTRIC-BUSES.pdf',
    std: 'IS 17017 (Part 1): 2018',
    stdTitle: 'Electric Vehicle Conductive AC and DC Charging System',
    edition: '1st Revision',
    secondary: 'IS 16046 (Part 2): 2018',
    secondaryTitle: 'Safety Requirements for Portable Sealed Secondary Lithium Cells (Battery Packs)',
    testing: 'AIS-038 (Rev 2) / AIS-153',
    testingTitle: 'Automotive Electric Vehicle Electrical Safety Requirements',
    qco: 'Ministry of Heavy Industries FAME-II / PM e-Bus Sewa Guidelines',
    gap: 'Thermal runaway propagation mitigation and battery enclosure fire suppression system (NFPA 855) missing.',
    remedy: 'Require AIS-038 Rev 2 Amendment 3 certified battery thermal safety and CCS Type 2 charging compliance under IS 17017.',
    spec: '12-meter low-floor (400mm floor height) monocoque city transit electric buses with 280 kWh LFP liquid-cooled battery pack, permanent magnet synchronous traction motor (250 kW peak), electronically controlled air suspension, and ADA wheelchair ramp.'
  },
  {
    name: 'Centrifugally Spun Reinforced Concrete NP3 Drainage Pipes 900mm',
    category: 'Drainage & Sewerage',
    quantity: '14 Kilometers (DN 900mm)',
    file: 'URBAN-DRAIN-2026-05-RCC-NP3-PIPES.pdf',
    std: 'IS 458: 2021',
    stdTitle: 'Precast Concrete Pipes (With and Without Reinforcement) - Specification',
    edition: '5th Revision',
    secondary: 'IS 3597: 1998',
    secondaryTitle: 'Methods of Test for Concrete Pipes',
    testing: 'IS 456: 2000',
    testingTitle: 'Plain and Reinforced Concrete Code',
    qco: 'DPIIT Concrete Pipes Quality Control Order',
    gap: 'Three-edge bearing test failure load (IS 458 Table 3) and hydrostatic pressure leakage test not witnessed.',
    remedy: 'Mandate ISI mark under IS 458 Class NP3 with barrel three-edge proof load test >= 44 kN/m.',
    spec: '900mm internal diameter centrifugally spun reinforced concrete pressure pipes Class NP3 with spigot and socket flexible rubber ring joints conforming to IS 458: 2021 for deep underground municipal stormwater and sewerage outfall.'
  },
  {
    name: 'Jal Jeevan Mission Rural Potable Water HDPE Pipes PE-100 PN-10',
    category: 'Water Supply Infrastructure',
    quantity: '65 Kilometers (DN 63mm to 200mm)',
    file: 'JJM-WATER-2026-06-HDPE-PIPES-PE100.pdf',
    std: 'IS 4984: 2016',
    stdTitle: 'Polyethylene Pipes for Water Supply - Specification',
    edition: '5th Revision',
    secondary: 'IS 7634 (Part 2): 2012',
    secondaryTitle: 'Code of Practice for Plastics Pipes Selection and Laying (HDPE)',
    testing: 'IS 2530: 1963',
    testingTitle: 'Methods of Test for Polyethylene Molding Materials and Compounds',
    qco: 'DPIIT Polyethylene Pipes (Quality Control) Order',
    gap: 'Carbon black dispersion test and 100-hour hydrostatic strength test at 80 deg C omitted in field verification.',
    remedy: 'Enforce Virgin PE-100 polymer raw material certification (IS 7328) with zero recycled plastic and IS 4984 ISI mark.',
    spec: 'High-Density Polyethylene (HDPE) pressure pipes manufactured from 100% virgin resin Grade PE-100, pressure rating PN-10 (1.0 MPa), with continuous blue co-extruded statutory identifying stripes conforming to IS 4984.'
  },
  {
    name: 'Perforated Acoustic Gypsum Board Ceilings for State Legislative Chambers',
    category: 'Civic Architecture',
    quantity: '5,500 Square Meters',
    file: 'PWD-CIVIC-2026-07-ACOUSTIC-CEILINGS.pdf',
    std: 'IS 2095 (Part 1): 2011',
    stdTitle: 'Gypsum Plaster Boards - Specification - Part 1: Plain Gypsum Plaster Boards',
    edition: '3rd Revision',
    secondary: 'IS 2542 (Part 1): 1978',
    secondaryTitle: 'Methods of Test for Gypsum Plaster, Concrete and Products',
    testing: 'IS 11050: 1984',
    testingTitle: 'Rating of Sound Insulation in Buildings and of Building Elements',
    qco: 'National Building Code (NBC 2016 Part 8 Acoustics)',
    gap: 'Noise Reduction Coefficient (NRC >= 0.70) test report from accredited reverberation chamber missing.',
    remedy: 'Mandate certified sound absorption test report as per ISO 354 and non-combustibility certification under BS 476 Part 4.',
    spec: '12.5mm square-edge perforated acoustic gypsum boards with 15% perforation area, non-woven acoustic tissue fleece backing, achieving minimum NRC 0.75 suspended on concealed hot-dip galvanized steel grid.'
  },
  {
    name: 'Grade 304 Stainless Steel Modular Bus Queue Shelters for Smart Transit',
    category: 'Urban Street Furniture',
    quantity: '120 Bus Shelters',
    file: 'MUNICIPAL-2026-08-BUS-QUEUE-SHELTER.pdf',
    std: 'IS 6911: 2017',
    stdTitle: 'Stainless Steel Plate, Sheet and Strip - Specification (First Revision)',
    edition: '1st Revision',
    secondary: 'IS 15997: 2012',
    secondaryTitle: 'Low Nickel Austenitic Stainless Steel Sheet and Strip for General Applications',
    testing: 'IS 1367 (Part 14): 2002',
    testingTitle: 'Technical Supply Conditions for Threaded Steel Fasteners - Stainless Steel Fasteners',
    qco: 'Ministry of Steel (Stainless Steel Products Quality Control Order)',
    gap: 'Supplier attempted quoting magnetic 200-series low-nickel stainless steel prone to rust in outdoor ambient.',
    remedy: 'Strictly enforce authentic Grade AISI 304 (IS 6911 X07Cr19Ni9) with minimum 8.0% Nickel and 18.0% Chromium.',
    spec: 'Modular transit passenger bus queue shelters fabricated from structural Grade 304 stainless steel tubes and sheets with satin brush finish, 8mm laminated solar-control safety glass roofing, and LED backlight transit maps.'
  },
  {
    name: 'Disaster Emergency Inflatable Rescue Boats with 40HP Outboard Motor',
    category: 'Disaster Relief & Flood Management',
    quantity: '60 Rescue Boats',
    file: 'DISASTER-MGMT-2026-09-RESCUE-BOATS.pdf',
    std: 'IS 13495: 1992 (Reaffirmed 2020)',
    stdTitle: 'Life Saving Appliances - Inflatable Rescue Boats - Specification',
    edition: '1st Revision',
    secondary: 'IS 1259: 1984',
    secondaryTitle: 'Vinyl Coated Fabrics',
    testing: 'ISO 6185-2 / SOLAS LSA Code',
    testingTitle: 'Inflatable Boats - Powered Boats with Engine Rating 15 kW to 30 kW',
    qco: 'National Disaster Management Authority (NDMA) Procurement Guidelines',
    gap: 'Multi-compartment inflation buoyancy test (remaining afloat with one chamber deflated) and drop test not specified.',
    remedy: 'Enforce SOLAS Chapter III LSA Code and IS 13495 compliance with 5-compartment heavy duty Hypalon/Neoprene fabric.',
    spec: '4.7-meter heavy-duty inflatable disaster rescue boat constructed from 1670 Dtex reinforced Hypalon/Neoprene with rigid aluminium roll-up floorboard, 5 independent air chambers, towing bridle, and 40HP 2-stroke OBM.'
  },
  {
    name: 'Canal Headworks Crest Radial Sluice Gates & Electromechanical Hoists',
    category: 'Irrigation & Water Resources',
    quantity: '8 Radial Gates (12m x 8m)',
    file: 'IRRIG-HEADWORKS-2026-10-RADIAL-GATES.pdf',
    std: 'IS 4622: 2003 (Reaffirmed 2019)',
    stdTitle: 'Recommendations for Structural Design of Radial Gates (Second Revision)',
    edition: '2nd Revision',
    secondary: 'IS 6938: 2005',
    secondaryTitle: 'Design of Rope Drum and Screw Hoists for Hydraulic Gates - Code of Practice',
    testing: 'IS 10096 (Parts 1-3)',
    testingTitle: 'Recommendations for Inspection, Testing and Maintenance of Radial Gates and Hoists',
    qco: 'Central Water Commission (CWC) Guidelines for Dam and Barrage Gates',
    gap: 'Trunnion hub self-lubricating bronze bushing material specifications and skin plate corrosion allowance missing.',
    remedy: 'Mandate trunnion spherical self-lubricating bronze bearing bush as per IS 4622 and 2mm minimum corrosion allowance.',
    spec: '12m x 8m structural steel radial crest gates designed for 10m hydraulic water head conforming to IS 4622 fabricated from IS 2062 Grade E250C with dual-drum twin-rope electrically operated hoisting mechanism.'
  },
  {
    name: 'Anganwadi Center Food-Grade Stainless Steel Cookware & Milk Cans',
    category: 'Child Development & Nutrition',
    quantity: '50,000 Kitchen Sets',
    file: 'WCD-NUTRITION-2026-11-STEEL-COOKWARE.pdf',
    std: 'IS 5522: 2014',
    stdTitle: 'Stainless Steel Sheets and Strips for Utensils - Specification',
    edition: '3rd Revision',
    secondary: 'IS 6911: 2017',
    secondaryTitle: 'Stainless Steel Plate, Sheet and Strip',
    testing: 'IS 14756: 2017',
    testingTitle: 'Stainless Steel Cooking Utensils - Specification',
    qco: 'DPIIT Stainless Steel Utensils (Quality Control) Order',
    gap: 'Heavy metal migration limit testing (Lead, Cadmium, Nickel leachability) under Food Safety Regulations omitted.',
    remedy: 'Enforce food-contact grade austenitic stainless steel Grade AISI 304 with mandatory ISI mark under IS 14756.',
    spec: 'Food-grade stainless steel institutional cookware set comprising 20L heavy-bottom pressure cooker, milk boiling urns with brass valves, and serving handis fabricated from IS 5522 Grade X04Cr19Ni9.'
  },
  {
    name: 'Off-Grid Hybrid Solar Micro-Grid Power Systems for Remote Tribal Hamlets',
    category: 'Rural Electrification',
    quantity: '85 Solar Micro-Grids',
    file: 'TRIBAL-ENERGY-2026-12-SOLAR-MICROGRID.pdf',
    std: 'IS 14286: 2010',
    stdTitle: 'Crystalline Silicon Terrestrial Photovoltaic Modules',
    edition: '2nd Revision',
    secondary: 'IS 16221: 2015',
    secondaryTitle: 'Safety Qualification of Photovoltaic Modules',
    testing: 'IS 1651: 2013',
    testingTitle: 'Stationary Cells and Batteries, Lead-Acid Type with Tubular Positive Plates',
    qco: 'MNRE Off-Grid Solar Applications Guidelines',
    gap: 'Battery round-trip watt-hour efficiency (minimum 85%) and IP55 outdoor balance-of-system enclosure missing.',
    remedy: 'Require 2V tubular gel lead-acid batteries conforming to IS 15549 with remote GSM telemetry tracking under IS 16221.',
    spec: '10 kWp standalone solar micro-grid comprising MNRE-certified mono PERC panels, 48V 1200Ah tubular gel battery bank, bi-directional hybrid MPPT solar inverter, and local 230V single-phase LT distribution network.'
  },
  {
    name: 'State Transport Bus Terminal P1.8 HD Indoor LED Video Displays',
    category: 'Passenger Information Systems',
    quantity: '24 LED Video Walls',
    file: 'TRANSPORT-PIDS-2026-13-LED-VIDEO-WALL.pdf',
    std: 'IS 13252 (Part 1): 2010',
    stdTitle: 'Information Technology Equipment - Safety',
    edition: '2nd Revision',
    secondary: 'IS 16102 (Part 1): 2012',
    secondaryTitle: 'Self-Ballasted LED-Lamps for General Lighting Services - Safety Requirements',
    testing: 'IS 16103: 2012',
    testingTitle: 'LED Modules for General Lighting',
    qco: 'MeitY Compulsory Registration Scheme (CRS) for Electronic Displays',
    gap: 'Missing MeitY CRS registration clause for digital signage displays exceeding 32 inches.',
    remedy: 'Enforce BIS CRS registration under IS 13252 and color temperature calibration uniformity test (>= 98%).',
    spec: 'Ultra-high-definition indoor passenger information LED video wall display (pixel pitch 1.8mm) with die-cast aluminium cabinets, refresh rate >= 3840 Hz, brightness >= 800 cd/m2, and redundant Novastar controllers.'
  },
  {
    name: 'Municipal 150 TPD Rotary Trommel Screens for Solid Waste Processing',
    category: 'Solid Waste Management',
    quantity: '6 Trommel Units',
    file: 'SWM-MUNICIPAL-2026-14-WASTE-TROMMELS.pdf',
    std: 'IS 12402: 1988',
    stdTitle: 'Industrial Wire Screens - Specification',
    edition: '1st Revision',
    secondary: 'IS 9220: 1979',
    secondaryTitle: 'Pumps and Separation Equipment',
    testing: 'IS 3177: 1999',
    testingTitle: 'Electric Overhead Travelling Cranes and Winches',
    qco: 'Solid Waste Management Rules 2016 (CPCB Norms)',
    gap: 'Screen mesh aperture perforation wear-resistant steel plate grade (Hardox / SAIL-Hard) not specified.',
    remedy: 'Mandate abrasion-resistant alloy steel perforated screen segments (minimum 400 BHN hardness) as per IS 12402.',
    spec: '150 Tonnes Per Day rotary cylindrical trommel screen (diameter 2.5m x length 10m) with interchangeable 35mm and 16mm perforated screening sections, heavy-duty trunnion roller drive, and integrated dust extraction hood.'
  },
  {
    name: 'Dual-Gun 120kW CCS2/CHAdeMO DC Fast EV Charging Stations',
    category: 'Electric Vehicle Infrastructure',
    quantity: '40 DC Fast Charging Stations',
    file: 'ENERGY-EV-2026-15-DC-FAST-CHARGER.pdf',
    std: 'IS 17017 (Part 1): 2018',
    stdTitle: 'Electric Vehicle Conductive Charging System - Part 1: General Requirements',
    edition: '1st Revision',
    secondary: 'IS 17017 (Part 23): 2021',
    secondaryTitle: 'DC Electric Vehicle Charging Station',
    testing: 'IS 17017 (Part 21/Sec 2)',
    testingTitle: 'Electric Vehicle Requirements for Conductive Connection to an A.C./D.C. Supply',
    qco: 'CEA Technical Standards for Connectivity of Distributed Generation / EVSE Guidelines',
    gap: 'Open Charge Point Protocol (OCPP 1.6J/2.0.1) interoperability and residual direct current monitoring missing.',
    remedy: 'Incorporate mandatory OCPP 2.0.1 cloud telemetry protocol and Type B RCD protection compliant with IS 17017 Part 23.',
    spec: '120kW dual-gun commercial DC fast electric vehicle charging station with liquid-cooled CCS Type 2 charging guns, dynamic power sharing (60kW + 60kW or 120kW single), 7-inch touch HMI, and RFID/UPI cashless billing.'
  },
  {
    name: 'District Central Archives Motorized Mobile Compactor Storage Racks',
    category: 'Government Records Management',
    quantity: '25 Heavy Compactor Blocks',
    file: 'ARCHIVES-2026-16-MOBILE-COMPACTOR.pdf',
    std: 'IS 1888: 1982',
    stdTitle: 'Method of Load Test on Soils for Foundation Shelving Structures',
    edition: '2nd Revision',
    secondary: 'IS 3312: 1984',
    secondaryTitle: 'Steel Shelving Racks (Adjustable Type)',
    testing: 'IS 2062: 2011',
    testingTitle: 'Structural Steel Standards',
    qco: 'DPIIT Steel Furniture and Storage (Quality Control) Order',
    gap: 'Anti-topple seismic locking device and shelf uniform distributed load rating (120 kg/shelf) not certified.',
    remedy: 'Mandate anti-tilt floor rail safety locks and CRCA steel sheet thickness >= 1.2mm conforming to IS 3312.',
    spec: 'Mechanically assisted hand-wheel and motorized mobile compactor storage systems fabricated from cold-rolled close-annealed (CRCA) steel sheet (IS 513) with central cylinder key locking and anti-rebound track safety.'
  },
  {
    name: 'Ice-Lined Refrigerators (ILR) for Universal Child Immunization Vaccines',
    category: 'Cold Chain Healthcare',
    quantity: '350 Cold Chain Units',
    file: 'HEALTH-COLDCHAIN-2026-17-VACCINE-ILR.pdf',
    std: 'IS 14756: 2017',
    stdTitle: 'Domestic and Commercial Refrigerators - Performance and Safety',
    edition: '1st Revision',
    secondary: 'IS 1391 (Part 1): 2017',
    secondaryTitle: 'Room Air Conditioners and Condensing Units',
    testing: 'WHO PQS E003/RF05',
    testingTitle: 'World Health Organization Performance, Quality and Safety Refrigeration Protocols',
    qco: 'Ministry of Health & Family Welfare National Cold Chain Guidelines',
    gap: 'Holdover time during power failure (> 48 hours at +43 deg C ambient) and CFC/HCFC-free refrigerant omitted.',
    remedy: 'Require WHO PQS certified holdover time exceeding 54 hours between +2 deg C to +8 deg C using green refrigerant R-600a.',
    spec: 'Top-opening horizontal Ice-Lined Vaccine Refrigerator (capacity 140L vaccine net storage) operating on 230V AC with integrated copper ice-lining jackets, solid state temperature data logger, and holdover time >= 48 hours.'
  },
  {
    name: 'High-Intensity Retro-Reflective Highway Traffic Informatory Signs',
    category: 'Highway Safety',
    quantity: '850 Overhead / Gantry Signboards',
    file: 'NHAI-TRAFFIC-2026-18-RETRO-REFLECTIVE-SIGNS.pdf',
    std: 'IS 7593: 1986',
    stdTitle: 'Specification for Retro-Reflective Tapes and Signs',
    edition: '1st Revision',
    secondary: 'IRC 67: 2022',
    secondaryTitle: 'Code of Practice for Road Signs (Indian Roads Congress)',
    testing: 'ASTM D4956 Type XI',
    testingTitle: 'Standard Specification for Retroreflective Sheeting for Traffic Control',
    qco: 'MoRTH Specifications for Road and Bridge Works Section 800',
    gap: 'Tender quoted basic Class A sheeting (IS 7593) instead of mandatory Microprismatic Type XI for high-speed highways.',
    remedy: 'Mandate Full-Cube Microprismatic Retro-Reflective Sheeting Type XI (IRC 67: 2022) with 10-year field warranty.',
    spec: 'Overhead and shoulder-mounted directional highway informatory signboards fabricated from 3mm composite aluminium panels with ASTM D4956 Type XI full-cube retro-reflective sheeting and anti-dew clear protective overlay.'
  },
  {
    name: 'Non-Woven Polypropylene Geotextile Bags for Flood Embankment Protection',
    category: 'River Protection & Geosynthetics',
    quantity: '250,000 Geo-Bags',
    file: 'FLOOD-GEOTEXTILE-2026-19-RIVER-PROTECTION.pdf',
    std: 'IS 16653: 2017',
    stdTitle: 'Geosynthetics - Geotextile Bags for Coastal and Waterways Protection - Specification',
    edition: '1st Revision',
    secondary: 'IS 13162 (Part 5): 1992',
    secondaryTitle: 'Geotextiles - Methods of Test - Determination of Tensile Properties using Wide Width Strip',
    testing: 'IS 14706: 1999',
    testingTitle: 'Geotextiles - Sampling and Preparation of Test Specimens',
    qco: 'Ministry of Textiles (Geotextiles Quality Control Order)',
    gap: 'UV degradation retention strength after 500 hours xenon arc exposure (< 80%) not verified in lab test.',
    remedy: 'Specify non-woven needle-punched polypropylene geo-bags conforming to IS 16653 with wide-width tensile strength >= 25 kN/m.',
    spec: 'Non-woven needle-punched 100% polypropylene geotextile sand-filled bags (dimensions 1.03m x 0.70m, 300 GSM) with double-chain UV-stabilized stitching compliant with IS 16653 for river training and embankment scour protection.'
  },
  {
    name: 'Ultrasonic Bulk Cold Water Meters with NB-IoT Smart Telemetry',
    category: 'Municipal Water Measurement',
    quantity: '1,500 Bulk Meters (DN 100 to 250mm)',
    file: 'URBAN-WATER-2026-20-ULTRASONIC-METERS.pdf',
    std: 'IS 779: 1994 (Reaffirmed 2020)',
    stdTitle: 'Water Meters (Domestic Type) - Specification',
    edition: '5th Revision',
    secondary: 'IS 6784: 1996 / ISO 4064',
    secondaryTitle: 'Method of Testing Water Meters',
    testing: 'IS 14846: 2000',
    testingTitle: 'Waterworks Valves and Testing Criteria',
    qco: 'Legal Metrology (Packaged Commodities & Measuring Instruments) Rules',
    gap: 'Dynamic turndown ratio (R400) and zero mechanical moving parts durability test missing.',
    remedy: 'Mandate ISO 4064 / OIML R49 Class 2 accuracy certification with IP68 submersible potted electronic housing.',
    spec: 'Flanged ultrasonic transit-time cold potable water meters (DN 150mm) Class 2 accuracy conforming to ISO 4064 / IS 6784 with bi-directional measurement, integrated Narrowband-IoT communication modem, and 10-year internal lithium battery.'
  },
  {
    name: 'Forest Patrol 4x4 Off-Road Electric Utility Vehicles',
    category: 'Forest & Wildlife Conservation',
    quantity: '30 Patrol Vehicles',
    file: 'FOREST-WILDLIFE-2026-21-ELECTRIC-PATROL.pdf',
    std: 'IS 17017 (Part 1): 2018',
    stdTitle: 'Electric Vehicle Conductive Charging System',
    edition: '1st Revision',
    secondary: 'IS 16046 (Part 2): 2018',
    secondaryTitle: 'Safety Requirements for Lithium Cells for EV Propulsion',
    testing: 'AIS-038 (Rev 2)',
    testingTitle: 'Electric Power Train Vehicles - Construction and Functional Safety',
    qco: 'Central Motor Vehicles Rules (CMVR) Type Approval',
    gap: 'Ingress protection against water wading (minimum 500mm water depth, IP67 powertrain) missing.',
    remedy: 'Mandate ARAI/ICAT certified powertrain with IP67 electric motor and AIS-038 thermal safety clearance.',
    spec: 'All-wheel drive 4x4 rugged off-road electric utility vehicles for forest sanctuaries with 20 kWh IP67 battery, 72V AC induction motor, 150 km range on rough terrain, silent operation (< 45 dB), and solar auxiliary canopy.'
  },
  {
    name: 'Pressure-Compensating Inline Agricultural Drip Irrigation Tubing',
    category: 'Agricultural Infrastructure',
    quantity: '2,000 Kilometers',
    file: 'AGRI-IRRIG-2026-22-DRIP-TUBING.pdf',
    std: 'IS 13488: 2008 (Reaffirmed 2021)',
    stdTitle: 'Irrigation Equipment - Emitting Pipe Systems - Specification',
    edition: '1st Revision',
    secondary: 'IS 12786: 1989',
    secondaryTitle: 'Irrigation Equipment - Polyethylene Pipes for Irrigation Laterals',
    testing: 'IS 13487: 1992',
    testingTitle: 'Irrigation Equipment - Emitters - Specification',
    qco: 'DPIIT Agricultural Irrigation Equipment (Quality Control) Order',
    gap: 'Coefficient of manufacturing variation (CV <= 0.05) and carbon black content (2.5% +/- 0.5%) unverified.',
    remedy: 'Enforce mandatory ISI mark under IS 13488 with pressure-compensating labyrinth drippers operating from 0.7 to 3.5 bar.',
    spec: '16mm outer diameter cylindrical pressure-compensating inline drip emitting pipes conforming to IS 13488 with 2.0 LPH discharge rate, 40cm emitter spacing, UV-stabilized linear low-density polyethylene (LLDPE) construction.'
  },
  {
    name: 'Compostable & Biodegradable Wet Organic Waste Garbage Bags',
    category: 'Municipal Sanitation',
    quantity: '5,000,000 Bags',
    file: 'MUNICIPAL-SWM-2026-23-COMPOSTABLE-BAGS.pdf',
    std: 'IS 17088: 2021',
    stdTitle: 'Plastics - Specification for Compostable Plastics',
    edition: '2nd Revision',
    secondary: 'IS 1070: 1992',
    secondaryTitle: 'Water for General Laboratory Use',
    testing: 'ISO 14855-1',
    testingTitle: 'Determination of the Ultimate Aerobic Biodegradability of Plastic Materials',
    qco: 'Plastic Waste Management Rules (MoEFCC & CPCB Mandatory Certification)',
    gap: 'Central Pollution Control Board (CPCB) compostable plastic manufacturing certificate clause omitted.',
    remedy: 'Strictly mandate CPCB EPR registration certificate and IS 17088 180-day 90% biodegradation test compliance.',
    spec: 'Biodegradable and compostable corn-starch based bio-plastic garbage collection bin liners (size 24x30 inches, thickness 40 microns) conforming to IS 17088 printed with QR code and statutory CPCB registration number.'
  },
  {
    name: '42-Meter Hydraulic Aerial Ladder Platform Fire Rescue Appliance',
    category: 'Municipal Fire Services',
    quantity: '4 Fire Appliances',
    file: 'FIRE-SERVICES-2026-24-AERIAL-LADDER-42M.pdf',
    std: 'IS 949: 1985 (Reaffirmed 2019)',
    stdTitle: 'Specification for Emergency Rescue Tender for Fire Brigade Use',
    edition: '2nd Revision',
    secondary: 'IS 951: 1987',
    secondaryTitle: 'Functional Requirements for Crash Fire Tender',
    testing: 'EN 1777 / NFPA 1901',
    testingTitle: 'Hydraulic Platforms for Fire Fighting and Rescue Services',
    qco: 'Standing Fire Advisory Council (SFAC) Directorate General Civil Defense Guidelines',
    gap: 'Cage safe working load (minimum 450 kg / 4 persons) and water monitor throw capacity (3,800 LPM) omitted.',
    remedy: 'Mandate rescue cage payload 500 kg, computerized outrigger auto-leveling, and 42m working height as per IS 949.',
    spec: '42-meter articulating telescopic boom hydraulic aerial ladder platform mounted on BS-VI 6x4 chassis with high-pressure bronze fire pump (4000 LPM @ 10 bar), remote electric water-foam monitor, and ultrasonic anti-collision cage sensors.'
  },
  {
    name: '7-Ply Low-Relaxation Uncoated Pre-Stressed Concrete Strands 15.2mm',
    category: 'Bridge Infrastructure',
    quantity: '1,200 Metric Tonnes',
    file: 'BRIDGE-PWD-2026-25-LRPC-STRANDS.pdf',
    std: 'IS 14268: 2022',
    stdTitle: 'Uncoated Stress Relieved Low Relaxation Seven-Ply Steel Strand for Prestressed Concrete',
    edition: '2nd Revision',
    secondary: 'IS 1785 (Part 1): 1983',
    secondaryTitle: 'Plain Hard-Drawn Steel Wire for Pre-Stressed Concrete',
    testing: 'IS 1608: 2018',
    testingTitle: 'Metallic Materials - Tensile Testing',
    qco: 'Ministry of Steel (Quality Control) Order for Pre-stressing Steels',
    gap: '1000-hour isothermal stress relaxation test certificate at 20 deg C (max 2.5% relaxation) missing.',
    remedy: 'Enforce Class 2 low-relaxation strands with minimum breaking load 260.7 kN under IS 14268 Table 1.',
    spec: '15.2mm nominal diameter 7-ply uncoated low-relaxation pre-stressed concrete steel strands conforming to IS 14268 Class 2 with characteristic tensile strength 1860 MPa for flyover segmental box girder bridges.'
  },
  {
    name: 'Multi-Zone Walk-Through Door Frame Metal Detectors (DFMD) for Courts',
    category: 'Judicial Security',
    quantity: '140 DFMD Units',
    file: 'COURT-SECURITY-2026-26-DFMD-SYSTEMS.pdf',
    std: 'IS 13252 (Part 1): 2010',
    stdTitle: 'Information Technology Equipment - Safety',
    edition: '2nd Revision',
    secondary: 'IS 14611: 1999',
    secondaryTitle: 'Metal Detectors - Walk-Through - Specification',
    testing: 'NILECJ-STD-0601.00',
    testingTitle: 'Walk-Through Metal Detectors for Use in Weapons Detection',
    qco: 'Ministry of Home Affairs (MHA) Standard Security Specifications',
    gap: 'Pacemaker safety certificate and multi-target simultaneous pin-pointing (minimum 33 zones) omitted.',
    remedy: 'Require 33-zone detection with zero dead zones, cardiac pacemaker safety compliance, and IS 14611 conformance.',
    spec: '33-zone multi-frequency microprocessor-controlled walk-through door frame metal detector conforming to IS 14611 with digital LED column target location, transit traffic counter, immune to external electrical noise, and battery backup.'
  },
  {
    name: 'Non-Toxic Wooden Educational Cognitive Toys for Anganwadis',
    category: 'Early Childhood Education',
    quantity: '75,000 Toy Kits',
    file: 'WCD-EDU-2026-27-WOODEN-TOYS.pdf',
    std: 'IS 9873 (Part 1): 2019',
    stdTitle: 'Safety of Toys - Part 1: Mechanical and Physical Properties',
    edition: '2nd Revision',
    secondary: 'IS 9873 (Part 2): 2017',
    secondaryTitle: 'Safety of Toys - Flammability',
    testing: 'IS 9873 (Part 3): 2020',
    testingTitle: 'Safety of Toys - Migration of Certain Elements (Toxic Heavy Metals)',
    qco: 'DPIIT Toys (Quality Control) Order, 2020 (Mandatory ISI Mark)',
    gap: 'Tender missing mandatory ISI Mark clause under DPIIT Toys QCO; heavy metal migration limits unspecified.',
    remedy: 'Enforce mandatory BIS License under Scheme-I with zero lead, mercury, or cadmium migration under IS 9873 Part 3.',
    spec: 'Educational wooden geometry sorting puzzles and counting abacus manufactured from natural seasoned rubberwood with non-toxic organic vegetable dyed finishes conforming strictly to IS 9873 (Parts 1, 2 & 3).'
  },
  {
    name: 'Medical Grade Reverse Osmosis Water Treatment Units for Dialysis',
    category: 'Specialized Healthcare',
    quantity: '25 Dialysis RO Units',
    file: 'HEALTH-DIALYSIS-2026-28-MEDICAL-RO.pdf',
    std: 'IS 16240: 2015',
    stdTitle: 'Reverse Osmosis Point of Use Water Treatment Systems',
    edition: '1st Revision',
    secondary: 'IS 10500: 2012',
    secondaryTitle: 'Drinking Water Specification',
    testing: 'AAMI / ISO 23500-3',
    testingTitle: 'Quality of Water for Haemodialysis and Related Therapies',
    qco: 'CDSCO Medical Device Guidelines for Dialysis Equipment',
    gap: 'Endotoxin bacteria threshold (< 0.25 EU/ml) and chemical disinfectant dead-leg elimination omitted.',
    remedy: 'Mandate ISO 23500-3 compliance with ultra-filtration endotoxin polisher and daily automated heat sanitization.',
    spec: 'Dual-pass reverse osmosis water purification plant (1,500 LPH) for 15-bed hemodialysis unit with automated 85 deg C hot water thermal disinfection, stainless steel 316L piping, and endotoxin monitoring.'
  },
  {
    name: 'Radial Tubeless Tyres 295/80 R22.5 for State Road Transport Buses',
    category: 'Automotive Components',
    quantity: '18,000 Tyres',
    file: 'TRANSPORT-TYRES-2026-29-BUS-RADIALS.pdf',
    std: 'IS 15636: 2012 (Reaffirmed 2022)',
    stdTitle: 'Automotive Vehicles - Pneumatic Tyres for Commercial Vehicles - Diagonal and Radial Ply',
    edition: '1st Revision',
    secondary: 'AIS-044 (Part 3)',
    secondaryTitle: 'Automotive Pneumatic Tyres Performance Requirements',
    testing: 'IS 15636 High Speed Test / Endurance Test',
    testingTitle: 'Endurance Performance for Commercial Vehicle Tyres',
    qco: 'DPIIT Pneumatic Tyres (Quality Control) Order',
    gap: 'Wet grip index and rolling resistance coefficient (RRC <= 5.5 N/kN) under AIS-142 standards missing.',
    remedy: 'Require mandatory ISI mark under IS 15636 with Star Rating Label certified by Bureau of Energy Efficiency.',
    spec: 'All-position commercial radial tubeless tyres size 295/80 R22.5 load index 152/148M conforming to IS 15636 with 4-belt steel casing, cut-and-chip resistant tread compound, and minimum guaranteed casing life of 150,000 km.'
  },
  {
    name: 'Heavy-Duty Smooth High-Density Polyethylene Geomembrane Liners 1.5mm',
    category: 'Water Conservation',
    quantity: '450,000 Square Meters',
    file: 'WATER-RESERVOIR-2026-30-GEOMEMBRANE.pdf',
    std: 'IS 16352: 2020',
    stdTitle: 'Geosynthetics - High Density Polyethylene (HDPE) Geomembranes - Specification',
    edition: '1st Revision',
    secondary: 'IS 15351: 2015',
    secondaryTitle: 'Laminated High Density Polyethylene Woven Geomembrane',
    testing: 'ASTM D5397',
    testingTitle: 'Stress Crack Resistance (SPCTL Test)',
    qco: 'Ministry of Textiles Geosynthetics Mandatory Order',
    gap: 'Environmental stress crack resistance (ESCR > 500 hours) and oxidative induction time (OIT > 100 min) omitted.',
    remedy: 'Enforce IS 16352 Type 1 smooth geomembrane manufactured from virgin resin with minimum carbon black 2.0%.',
    spec: '1.5mm thick smooth black HDPE geomembrane manufactured from 100% virgin polymer conforming to IS 16352 with dual-wedge thermal fusion welding, air pressure test channels, for municipal raw water storage reservoirs.'
  },
  {
    name: 'Outdoor Calisthenics & Fitness Gymnasium Equipment for Public Parks',
    category: 'Urban Recreational Infrastructure',
    quantity: '200 Open Gym Sets',
    file: 'PARKS-FITNESS-2026-31-OPEN-GYM.pdf',
    std: 'IS 9873: 2019',
    stdTitle: 'Safety Guidelines for Recreational Physical Equipment',
    edition: '1st Revision',
    secondary: 'IS 1239 (Part 1): 2004',
    secondaryTitle: 'Steel Tubes for Structural Applications',
    testing: 'EN 16630',
    testingTitle: 'Permanently Installed Outdoor Fitness Equipment - Safety Requirements and Test Methods',
    qco: 'State Urban Municipal Safety By-Laws',
    gap: 'Finger entrapment protection clearance (less than 8mm or greater than 25mm) and bearing water ingress omitted.',
    remedy: 'Mandate EN 16630 and IS 1239 Heavy Grade GI structural pipe fabrication with sealed marine-grade bearings.',
    spec: 'Heavy-duty vandal-resistant outdoor open-gym equipment sets (Air Walker, Chest Press, Lat Pull-Down) fabricated from Class C galvanized steel tubes with electrostatically baked polyester powder coating and self-lubricating sealed bearings.'
  },
  {
    name: '120-Minute Fire-Resistant Glazed Emergency Exit Doors',
    category: 'Fire Safety & Life Safety',
    quantity: '320 Fire Door Sets',
    file: 'CIVIC-FIRE-2026-32-FIRE-DOORS.pdf',
    std: 'IS 3614: 2021',
    stdTitle: 'Fire Doors - Specification (First Revision)',
    edition: '1st Revision',
    secondary: 'IS 2202 (Part 1): 1999',
    secondaryTitle: 'Wooden Flush Door Shutters (Solid Core Type)',
    testing: 'IS/ISO 3008: 2007',
    testingTitle: 'Fire Resistance Tests - Door and Shutter Assemblies',
    qco: 'National Building Code 2016 Part 4 Life Safety Directive',
    gap: 'Tender cited obsolete IS 3614 Part 1: 1992 test standard and lacked intumescent smoke seal specification.',
    remedy: 'Mandate CBRI Roorkee or accredited laboratory 120-minute stability and integrity test report under IS 3614: 2021.',
    spec: '2-hour (120-minute) fire-rated double leaf galvanized steel flush doors conforming to IS 3614: 2021 with mineral wool honeycomb core, panic exit crash hardware, intumescent fire smoke seals, and vision lite fire glass.'
  }
];

console.log(`Loaded ${DEPT_TOPICS.length} Government Department topics.`);
