import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { DEMO_USERS, DEMO_PASSWORD } from './demoUsers.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Helper for dates
const daysAgo = (days) => new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

// 32 Procurement Officer Topics
const PO_TOPICS = [
  {
    name: '100W Outdoor LED Street Light Luminaires',
    category: 'Electrical & Lighting',
    quantity: '2,500 Luminaires',
    file: 'CPWD-NIT-2026-01-LED-STREETLIGHT.pdf',
    std: 'IS 10322 (Part 5/Sec 3): 2012',
    stdTitle: 'Luminaires - Particular Requirements - Luminaires for Road and Street Lighting',
    edition: '3rd Revision',
    secondary: 'IS 15885 (Part 2/Sec 13): 2012',
    secondaryTitle: 'Electronic Controlgear for LED Modules',
    testing: 'IS 16107 (Part 2/Sec 1): 2012',
    testingTitle: 'LED Luminaire Photometric and Electrical Performance',
    qco: 'MeitY Compulsory Registration Scheme (CRS) & BEE Star Labeling Mandate',
    gap: 'Tender missing mandatory 10kV surge protection compliance under IS 10322 and NABL photobiological safety test report.',
    remedy: 'Mandate Type Test Certificate as per IS 16107 and 10kV SPD under IS 10322.',
    spec: 'Supply and installation of 100W pressure die-cast aluminium outdoor LED street light luminaires with IP66 ingress protection, system efficacy >= 130 lm/W, CRI > 70, CCT 5700K, and 10kV internal surge protection device.'
  },
  {
    name: '33/11kV Substation 5 MVA Power Transformer',
    category: 'Power & Distribution',
    quantity: '4 Units',
    file: 'CPWD-ELEC-2026-02-POWER-TRANSFORMER.pdf',
    std: 'IS 2026 (Parts 1-5): 2011',
    stdTitle: 'Power Transformers - General, Temperature Rise, Insulation & Dielectric Tests',
    edition: '4th Revision',
    secondary: 'IS 1180 (Part 1): 2014',
    secondaryTitle: 'Outdoor Type Oil Immersed Distribution Transformers',
    testing: 'IS 335: 2018',
    testingTitle: 'Uninhibited Mineral Insulating Oils for Transformers',
    qco: 'DPIIT Transformers Quality Control Order, 2024',
    gap: 'Tender cites obsolete IS 2026: 1977 temperature limits and lacks BEE maximum loss capitalization formula.',
    remedy: 'Update to IS 2026: 2011 and enforce mandatory BIS ISI License Scheme-I under QCO 2024.',
    spec: '33/11kV, 5 MVA, 3-Phase, 50 Hz, ONAN cooled outdoor type oil-immersed power transformer with copper winding, on-load tap changer (+5% to -15%), and uninhibited mineral oil conforming to IS 335.'
  },
  {
    name: 'High-Yield Strength TMT Reinforcement Steel Bars Fe 500D',
    category: 'Structural Materials',
    quantity: '750 Metric Tonnes',
    file: 'CPWD-CIVIL-2026-03-TMT-STEEL-BARS.pdf',
    std: 'IS 1786: 2008 (Reaffirmed 2023)',
    stdTitle: 'High Strength Deformed Steel Bars and Wires for Concrete Reinforcement',
    edition: '4th Revision',
    secondary: 'IS 2062: 2011',
    secondaryTitle: 'Hot Rolled Medium and High Tensile Structural Steel',
    testing: 'IS 1608 (Part 1): 2018',
    testingTitle: 'Metallic Materials - Tensile Testing at Ambient Temperature',
    qco: 'Ministry of Steel (Quality Control) Mandatory Enforcement Order',
    gap: 'Missing requirement for mandatory sulfur and phosphorus combined maximum limit of 0.075% for earthquake ductility.',
    remedy: 'Specify strict chemical limits and bend/rebend test verification as per IS 1786 Fe 500D.',
    spec: 'Thermo-Mechanically Treated (TMT) high strength deformed steel reinforcement bars Grade Fe 500D (sizes 8mm to 32mm) with minimum 16% elongation and 1.10 TS/YS ratio for seismic zone IV.'
  },
  {
    name: 'Ordinary Portland Cement 53 Grade',
    category: 'Cement & Concrete',
    quantity: '1,200 Metric Tonnes',
    file: 'CPWD-CIVIL-2026-04-CEMENT-OPC53.pdf',
    std: 'IS 269: 2015 (Amended 2021)',
    stdTitle: 'Ordinary Portland Cement - Specification (incorporating 33, 43 and 53 Grades)',
    edition: '6th Revision',
    secondary: 'IS 4031 (Parts 1-15)',
    secondaryTitle: 'Methods of Physical Tests for Hydraulic Cement',
    testing: 'IS 4032: 1985',
    testingTitle: 'Method of Chemical Analysis of Hydraulic Cement',
    qco: 'DPIIT Cement (Quality Control) Order',
    gap: 'Tender cited withdrawn separate standard IS 12269: 1987 instead of current harmonized standard IS 269: 2015.',
    remedy: 'Amend tender to cite IS 269: 2015 (53 Grade) and require weekly manufacturer test certificate.',
    spec: 'Supply of fresh 53 Grade Ordinary Portland Cement in 50 kg HDPE bags with minimum 28-day compressive strength of 53 MPa and initial setting time not less than 30 minutes.'
  },
  {
    name: 'Microprocessor Addressable Fire Alarm & Smoke Detection System',
    category: 'Fire Safety & Life Safety',
    quantity: '1 Complete Central System',
    file: 'CPWD-ELEC-2026-05-FIRE-DETECTION.pdf',
    std: 'IS 2189: 2008 (Reaffirmed 2019)',
    stdTitle: 'Selection, Installation and Maintenance of Automatic Fire Detection and Alarm System',
    edition: '4th Revision',
    secondary: 'IS 11360: 1985',
    secondaryTitle: 'Specification for Smoke Detectors for Use in Automatic Electrical Fire Alarm System',
    testing: 'IS 12459: 2004',
    testingTitle: 'Fire Safety in Buildings - Code of Practice for Cable Penetration Seals',
    qco: 'National Building Code of India (NBC 2016 Part 4)',
    gap: 'Loop sounder circuit decibel ratings omitted; battery standby duration specified as only 4 hours instead of statutory 24 hours plus 30 mins alarm.',
    remedy: 'Align standby power battery sizing to IS 2189 Clause 6.8 mandatory 24-hour quiescent operation.',
    spec: 'Networked addressable 4-loop fire alarm control panel with dual-optical smoke sensors, multi-criteria thermal detectors, loop-powered sounder beacons (95 dB), and fault-tolerant BACnet interface.'
  },
  {
    name: 'Ductile Iron K9 Pressure Pipes for Municipal Potable Water',
    category: 'Piping & Water Supply',
    quantity: '8.5 Kilometers (DN 300 & 450mm)',
    file: 'CPWD-WATER-2026-06-DI-PIPES-K9.pdf',
    std: 'IS 8329: 2000 (Reaffirmed 2020)',
    stdTitle: 'Centrifugally Cast (Ductile) Iron Pressure Pipes for Water, Gas and Sewage',
    edition: '3rd Revision',
    secondary: 'IS 9523: 2000',
    secondaryTitle: 'Ductile Iron Fittings for Pressure Pipes for Water, Gas and Sewage',
    testing: 'IS 5382: 2018',
    testingTitle: 'Rubber Sealing Rings for Gas Mains, Water Mains and Sewers',
    qco: 'Ministry of Steel DI Pipes Quality Control Order',
    gap: 'Internal Portland cement mortar lining thickness and hydraulic factory test pressure (5.0 MPa) unverified in inspection schedule.',
    remedy: 'Mandate third-party factory witness hydrostatic test and cement mortar lining adherence as per IS 8329 Clause 11.',
    spec: 'Centrifugally cast Ductile Iron K9 spigot and socket pipes with internal sulphate resisting cement mortar lining and external metallic zinc coating with finishing bitumen layer as per IS 8329.'
  },
  {
    name: 'Water-Cooled Centrifugal Chiller Plant 400 TR',
    category: 'HVAC & Mechanical',
    quantity: '2 Units (400 TR each)',
    file: 'CPWD-HVAC-2026-07-CENTRIFUGAL-CHILLER.pdf',
    std: 'IS 8148: 2003 (Reaffirmed 2019)',
    stdTitle: 'Packaged Air Conditioners - Specification',
    edition: '2nd Revision',
    secondary: 'IS 1391 (Part 2): 2018',
    secondaryTitle: 'Room Air Conditioners - Split Air Conditioners',
    testing: 'IS 659: 1964',
    testingTitle: 'Safety Code for Mechanical Refrigeration',
    qco: 'BEE Mandatory Star Rating / Energy Conservation Building Code (ECBC)',
    gap: 'Refrigerant GWP threshold omitted; Integrated Part Load Value (IPLV) not benchmarked against ECBC norms.',
    remedy: 'Incorporate zero-ODP non-toxic eco-friendly refrigerant R-134a/R-513A and enforce minimum COP >= 6.3 under IS 8148.',
    spec: '400 TR high-efficiency water-cooled centrifugal liquid chillers with variable frequency drive (VFD), flooded evaporator, marine water boxes, and microchannel economizer achieving full load COP > 6.5.'
  },
  {
    name: 'Medical Gas Pipeline System (MGPS) for 500-Bed Govt Hospital',
    category: 'Healthcare Infrastructure',
    quantity: '1 Turnkey Hospital Facility',
    file: 'AIIMS-ENG-2026-08-MGPS-PIPELINE.pdf',
    std: 'IS 15001: 2002 (Reaffirmed 2021)',
    stdTitle: 'Medical Gas Pipeline Systems - Terminal Units and Non-Interchangeable Screw-Threaded Connectors',
    edition: '1st Revision',
    secondary: 'IS 7285 (Part 2): 2017',
    secondaryTitle: 'Refillable Seamless Steel Gas Cylinders',
    testing: 'IS 1239 (Part 1): 2004',
    testingTitle: 'Steel Tubes, Tubulars and Other Wrought Steel Fittings',
    qco: 'Medical Devices Rules / PESO Gas Cylinder Rules',
    gap: 'Cross-connection safety protocol and terminal quick-connect non-interchangeability check not specified.',
    remedy: 'Mandate gas-specific pin-index terminal outlets strictly compliant with IS 15001 to eliminate gas cross-over hazards.',
    spec: 'Turnkey medical gas pipeline distribution for Oxygen, Nitrous Oxide, Medical Air (4 bar & 7 bar), and Surgical Vacuum with seamless deoxidized copper tubing conforming to BS EN 13348 and IS 15001 gas terminal outlets.'
  },
  {
    name: '500kWp Grid-Connected Rooftop Solar PV Generation System',
    category: 'Renewable Energy',
    quantity: '500 kWp Plant',
    file: 'CPWD-SOLAR-2026-09-ROOFTOP-PV.pdf',
    std: 'IS 14286: 2010 / IEC 61215: 2005',
    stdTitle: 'Design Qualification and Type Approval for Crystalline Silicon Terrestrial Photovoltaic Modules',
    edition: '2nd Revision',
    secondary: 'IS 16221 (Part 2): 2015',
    secondaryTitle: 'Safety Qualification of Photovoltaic (PV) Modules',
    testing: 'IS 16169: 2014 / IEC 62116',
    testingTitle: 'Utility-Interconnected Photovoltaic Inverters - Anti-Islanding Test',
    qco: 'MNRE Solar Photovoltaics (Quality Control) Order, 2017',
    gap: 'Solar modules ALMM (Approved List of Models and Manufacturers) mandate clause missing in tender BOQ.',
    remedy: 'Incorporate statutory requirement that all PV modules must be listed on MNRE ALMM List-I and certified under IS 14286.',
    spec: '500 kWp grid-interactive rooftop solar power plant with Monocrystalline PERC half-cut PV modules (minimum 540Wp, efficiency >= 21%) and multi-MPPT string inverters compliant with IS 16221 & IS 16169.'
  },
  {
    name: 'Viscosity Grade VG-30 Paving Bitumen for Arterial Highway',
    category: 'Highway & Roads',
    quantity: '400 Metric Tonnes',
    file: 'CPWD-ROAD-2026-10-PAVING-BITUMEN.pdf',
    std: 'IS 73: 2018',
    stdTitle: 'Paving Bitumen - Specification (4th Revision)',
    edition: '4th Revision',
    secondary: 'IS 1201 to IS 1220: 1978',
    secondaryTitle: 'Methods of Testing Tar and Bituminous Materials',
    testing: 'IS 8887: 2018',
    testingTitle: 'Bitumen Emulsion for Roads (Cationic Type)',
    qco: 'Ministry of Road Transport and Highways (MoRTH) Section 500',
    gap: 'Penetration-graded bitumen cited in draft schedule instead of statutory Viscosity Graded (VG-30) as required by IS 73.',
    remedy: 'Enforce absolute viscosity at 60 deg C (2400 to 3600 Poises) and kinematic viscosity as per IS 73: 2018 Table 1.',
    spec: 'Bulk supply of Viscosity Grade VG-30 refinery-sourced paving bitumen with minimum softening point 47 deg C, penetration at 25 deg C >= 45, and absolute viscosity at 60 deg C >= 2400 Poises for Dense Bituminous Macadam.'
  },
  {
    name: '11kV Grade Cross-Linked Polyethylene (XLPE) Power Cables',
    category: 'Cables & Conductors',
    quantity: '12,000 Meters',
    file: 'CPWD-ELEC-2026-11-11KV-XLPE-CABLES.pdf',
    std: 'IS 7098 (Part 2): 2011',
    stdTitle: 'Crosslinked Polyethylene Insulated Thermoplastic Sheathed Cables - For Working Voltages from 3.3 kV up to and including 33 kV',
    edition: '2nd Revision',
    secondary: 'IS 5831: 1984',
    secondaryTitle: 'PVC Insulation and Sheath of Electric Cables',
    testing: 'IS 10810 (Parts 1-64)',
    testingTitle: 'Methods of Test for Cables',
    qco: 'DPIIT Electric Cables (Quality Control) Order',
    gap: 'Flame retardant low smoke (FRLS) outer sheath test parameters and partial discharge limits omitted.',
    remedy: 'Mandate FRLS properties as per IS 7098 (Part 2) Category C2 with max smoke density 60% and oxygen index >= 29.',
    spec: '11kV (E) grade, 3-Core x 300 sq.mm stranded compact circular Aluminium conductor, screened, XLPE insulated, inner PVC taped, galvanized steel flat strip armoured, extruded FRLS PVC outer sheathed cable.'
  },
  {
    name: '16-Passenger High-Speed Gearless Lifts for Multi-Storey Complex',
    category: 'Elevators & Escalators',
    quantity: '6 Elevators',
    file: 'CPWD-MECH-2026-12-PASSENGER-LIFTS.pdf',
    std: 'IS 14665 (Parts 1-5): 2000',
    stdTitle: 'Electric Traction Lifts - Outline Dimensions, Components, Safety & Inspection',
    edition: '1st Revision',
    secondary: 'IS 15785: 2007',
    secondaryTitle: 'Code of Practice for Installation and Maintenance of Lift without Machine Room (MRL)',
    testing: 'IS 14665 (Part 2/Sec 1)',
    testingTitle: 'Code of Practice for Installation, Operation and Maintenance of Electric Passenger Lifts',
    qco: 'State Lift Acts / Central Electricity Authority Safety Regulations',
    gap: 'Automatic Rescue Device (ARD) with audio-visual announcement and seismic counterweight retainer bracket omitted.',
    remedy: 'Incorporate mandatory emergency battery-operated ARD and seismic derailment switches compliant with IS 14665.',
    spec: '16-passenger (1088 kg) high-speed 2.5 m/s machine-room-less (MRL) gearless permanent magnet synchronous motor (PMSM) traction elevators with regenerative drive, full collective microprocessor control, and ARD.'
  },
  {
    name: 'Industrial Safety Helmets & Full Body Harness for Construction',
    category: 'Personal Protective Equipment',
    quantity: '3,000 Safety Kits',
    file: 'CPWD-SAFETY-2026-13-PPE-HELMETS.pdf',
    std: 'IS 2925: 1984 (Reaffirmed 2019)',
    stdTitle: 'Specification for Industrial Safety Helmets',
    edition: '2nd Revision',
    secondary: 'IS 3521 (Part 1): 2021',
    secondaryTitle: 'Personal Protective Equipment against Falls from a Height - Full Body Harnesses',
    testing: 'IS 15844: 2010',
    testingTitle: 'Leather and Safety Footwear Standards',
    qco: 'DPIIT Personal Protective Equipment (Quality Control) Order',
    gap: 'Tender failed to mandate ISI mark on safety helmets and omitted shock absorption impact testing clause.',
    remedy: 'Mandate ISI mark under IS 2925 and certified dual-lanyard shock absorber harness conforming to IS 3521.',
    spec: 'Heavy-duty high-density polyethylene (HDPE) industrial safety helmets conforming to IS 2925 with 6-point textile cradle, adjustable ratchet nape, electrical insulation up to 2000V, and Class A full body safety harnesses.'
  },
  {
    name: '11kV 25kA Indoor Vacuum Circuit Breaker (VCB) Switchgear',
    category: 'Electrical Switchgear',
    quantity: '8 HT Switchgear Panels',
    file: 'CPWD-ELEC-2026-14-11KV-VCB-PANELS.pdf',
    std: 'IS 13118: 1991 / IEC 62271-100',
    stdTitle: 'General Requirements for Circuit-Breakers for Voltages Above 1000 V',
    edition: '1st Revision',
    secondary: 'IS 3427: 1997 / IEC 62271-200',
    secondaryTitle: 'AC Metal-Enclosed Switchgear and Controlgear',
    testing: 'IS 12729: 1993',
    testingTitle: 'Common Clauses for High-Voltage Switchgear and Controlgear Standards',
    qco: 'CEA (Measures Relating to Safety and Electric Supply) Regulations',
    gap: 'Internal arc classification (IAC AFLR 25kA 1 sec) omitted; numerical relay communication protocol not specified.',
    remedy: 'Mandate IAC AFLR 25kA 1-second certified type test and IEC 61850 compliant numerical overcurrent relays.',
    spec: '11kV, 1250A, 25kA for 3 seconds indoor metal-clad horizontal drawout vacuum circuit breaker panel with vacuum interrupters, internal arc classification IAC AFLR 25kA 1s, and multi-function numerical protection.'
  },
  {
    name: 'Hot-Rolled Galvanized Structural Steel Sections for Logistics Hub',
    category: 'Structural Steel',
    quantity: '600 Metric Tonnes',
    file: 'CPWD-CIVIL-2026-15-STRUCTURAL-STEEL.pdf',
    std: 'IS 2062: 2011 (Reaffirmed 2021)',
    stdTitle: 'Hot Rolled Medium and High Tensile Structural Steel - Specification',
    edition: '7th Revision',
    secondary: 'IS 4759: 1996',
    secondaryTitle: 'Hot-Dip Zinc Coatings on Structural Steel and Other Allied Products',
    testing: 'IS 800: 2007',
    testingTitle: 'General Construction in Steel - Code of Practice',
    qco: 'Ministry of Steel (Steel Products Quality Control Order)',
    gap: 'Minimum zinc coating thickness not specified; charpy V-notch impact testing at sub-zero temperatures omitted.',
    remedy: 'Enforce Grade E250 Quality BR under IS 2062 and minimum 610 g/m2 hot-dip zinc coating as per IS 4759.',
    spec: 'Hot-rolled structural steel beams, channels, and angles conforming to IS 2062 Grade E250 BR with minimum yield strength 250 MPa, Charpy impact tested at 0 deg C, hot-dip galvanized to minimum 86 microns coating.'
  },
  {
    name: 'CPVC Pipes & Fittings for Hot and Cold Potable Water Plumbing',
    category: 'Plumbing & Sanitation',
    quantity: '25,000 Meters',
    file: 'CPWD-PLUMB-2026-16-CPVC-PIPES.pdf',
    std: 'IS 15778: 2007 (Reaffirmed 2022)',
    stdTitle: 'Chlorinated Polyvinyl Chloride (CPVC) Pipes for Potable Hot and Cold Water Distribution Supplies',
    edition: '1st Revision',
    secondary: 'IS 2465: 1984',
    secondaryTitle: 'Vent Pipes for Solvent Welded Plumbing',
    testing: 'IS 12235 (Parts 1-19)',
    testingTitle: 'Methods of Test for Unplasticized PVC Pipes for Cold Water Services',
    qco: 'DPIIT Pipes and Fittings (Quality Control) Order',
    gap: 'Hydrostatic burst pressure test at 82 deg C and NSF/ANSI 61 toxicology compliance clause missing.',
    remedy: 'Mandate ISI mark under IS 15778 Class 1 (SDR 11) and Class 2 (SDR 13.5) with hydrostatic pressure certification.',
    spec: 'Chlorinated Polyvinyl Chloride (CPVC) pipes for hot and cold internal domestic water distribution Class 1 (SDR 11) conforming to IS 15778 with solvent welded fittings matching ASTM F439.'
  },
  {
    name: 'Smart Three-Phase Static Prepaid Electricity Energy Meters',
    category: 'Smart Metering & IoT',
    quantity: '10,000 Smart Meters',
    file: 'CPWD-ELEC-2026-17-SMART-METERS.pdf',
    std: 'IS 16444 (Part 1): 2015',
    stdTitle: 'A.C. Static Direct Connected Watt-Hour Smart Meters Class 1 and 2',
    edition: '1st Revision',
    secondary: 'IS 15959 (Part 2): 2016',
    secondaryTitle: 'Data Exchange for Meter Reading, Tariff and Load Control - Companion Specification',
    testing: 'IS 13779: 1999',
    testingTitle: 'AC Static Watt-Hour Meters Class 1 and 2',
    qco: 'Ministry of Power Mandatory Smart Meter Rollout Notification',
    gap: 'Cyber security cryptography standards and DLMS/COSEM communication interoperability tests missing.',
    remedy: 'Enforce IS 15959 Category D compliance and secure key exchange algorithms as per CEA Smart Meter specifications.',
    spec: 'Three-phase 4-wire static smart prepayment energy meters Class 1.0 accuracy conforming to IS 16444 (Part 1) with integrated 4G-LTE/NB-IoT modem, optical communication port, and bi-directional disconnect relay.'
  },
  {
    name: '6A/16A Modular Electrical Switches and Shuttered Socket Outlets',
    category: 'Building Electricals',
    quantity: '45,000 Switch/Socket Units',
    file: 'CPWD-ELEC-2026-18-MODULAR-SWITCHES.pdf',
    std: 'IS 3854: 1997 (Reaffirmed 2021)',
    stdTitle: 'Switches for Domestic and Similar Certain Fixed Electrical Installations - Specification',
    edition: '2nd Revision',
    secondary: 'IS 1293: 2019',
    secondaryTitle: 'Plugs and Socket-Outlets of Rated Voltage up to and including 250 Volts',
    testing: 'IS 9537 (Part 3): 1983',
    testingTitle: 'Conduits for Electrical Installations - Rigid Plain Conduits of Insulating Materials',
    qco: 'DPIIT Electrical Accessories (Quality Control) Order',
    gap: 'Child-proof internal shutter mechanism on 16A 3-pin sockets not enforced; glow wire flammability omitted.',
    remedy: 'Mandate ISI mark under IS 3854 & IS 1293 with mandatory safety shutter and 850 deg C glow wire test rating.',
    spec: 'Polycarbonate flame-retardant modular rocker switches (6A & 16A) compliant with IS 3854 and 3-pin shuttered universal socket outlets compliant with IS 1293 mounted on powder-coated GI concealed backboxes.'
  },
  {
    name: 'Commercial Water Purification Reverse Osmosis (RO) Plant 10,000 LPH',
    category: 'Water Treatment',
    quantity: '2 Plants',
    file: 'CPWD-WATER-2026-19-COMMERCIAL-RO-PLANT.pdf',
    std: 'IS 16240: 2015',
    stdTitle: 'Reverse Osmosis Based Point-of-Use Water Treatment Systems',
    edition: '1st Revision',
    secondary: 'IS 10500: 2012 (Amended 2021)',
    secondaryTitle: 'Drinking Water - Specification',
    testing: 'IS 3025 (Parts 1-60)',
    testingTitle: 'Methods of Sampling and Test (Physical and Chemical) for Water and Wastewater',
    qco: 'National Green Tribunal (NGT) Water Purifier Efficiency Guidelines',
    gap: 'Permissible water recovery ratio set at 35% instead of statutory NGT/BIS mandated minimum 60% recovery.',
    remedy: 'Require energy-efficient high-recovery polyamide membranes achieving >= 60% recovery under IS 16240.',
    spec: '10,000 Litres Per Hour industrial RO water purification plant with multi-grade sand filter, activated carbon polisher, anti-scalant dosing, thin-film composite polyamide membranes, and automatic CIP skid.'
  },
  {
    name: 'Ready-Mixed Concrete (RMC) M35 / M40 Grade for Institutional Complex',
    category: 'Structural Concrete',
    quantity: '8,500 Cubic Meters',
    file: 'CPWD-CIVIL-2026-20-RMC-CONCRETE.pdf',
    std: 'IS 4926: 2003 (Reaffirmed 2019)',
    stdTitle: 'Ready-Mixed Concrete - Code of Practice',
    edition: '2nd Revision',
    secondary: 'IS 456: 2000 (Plain and Reinforced Concrete)',
    secondaryTitle: 'Code of Practice for Plain and Reinforced Concrete',
    testing: 'IS 516 (Part 1/Sec 1): 2021',
    testingTitle: 'Hardened Concrete - Methods of Test - Compressive Strength',
    qco: 'Quality Council of India (QCI) RMC Plant Certification Mandate',
    gap: 'Transit mixer transit duration limit and slump retention at discharge point (IS 4926 Cl. 6.2) not specified.',
    remedy: 'Mandate automated batching printout per truck and QCI-certified batching plant sourcing under IS 4926.',
    spec: 'Design mix Ready-Mixed Concrete Grade M35/M40 using 20mm graded aggregates, fly-ash blended cement (IS 1489), and polycarboxylate ether superplasticizer with initial slump 120-150mm at delivery point.'
  },
  {
    name: 'Precast Autoclaved Aerated Concrete (AAC) Blocks for Masonry',
    category: 'Building Materials',
    quantity: '350,000 Blocks',
    file: 'CPWD-CIVIL-2026-21-AAC-BLOCKS.pdf',
    std: 'IS 2185 (Part 3): 1984 (Reaffirmed 2020)',
    stdTitle: 'Concrete Masonry Units - Part 3: Autoclaved Cellular (Aerated) Concrete Blocks',
    edition: '1st Revision',
    secondary: 'IS 1077: 1992',
    secondaryTitle: 'Common Burnt Clay Building Bricks',
    testing: 'IS 6441 (Parts 1-9)',
    testingTitle: 'Methods of Test for Autoclaved Cellular Concrete Products',
    qco: 'Green Building GRIHA / MoEFCC Fly Ash Utilization Notification',
    gap: 'Dry density class (Grade 1 vs Grade 2) and drying shrinkage limit omitted in masonry schedule.',
    remedy: 'Specify Grade 1 AAC blocks with oven dry density 551-650 kg/m3 and compressive strength >= 4.0 N/mm2 as per IS 2185.',
    spec: 'Autoclaved Aerated Concrete (AAC) masonry blocks conforming to IS 2185 (Part 3) Grade 1, thermal conductivity k <= 0.16 W/m.K, with polymer-modified thin-bed masonry mortar conforming to IS 1661.'
  },
  {
    name: 'Landing Valves and Branch Pipes for Wet Riser Fire Fighting',
    category: 'Fire Safety & Life Safety',
    quantity: '180 Sets',
    file: 'CPWD-FIRE-2026-22-HYDRANT-VALVES.pdf',
    std: 'IS 5290: 1993 (Reaffirmed 2019)',
    stdTitle: 'Specification for Landing Valves (Internal Hydrants)',
    edition: '3rd Revision',
    secondary: 'IS 903: 1993',
    secondaryTitle: 'Fire Hose Delivery Couplings, Branch Pipe, Nozzles and Strainers',
    testing: 'IS 636: 2018',
    testingTitle: 'Non-Percolating Flexible Fire Fighting Delivery Hose',
    qco: 'National Building Code 2016 Part 4 / BIS ISI Mandate',
    gap: 'Gunmetal grade (Leaded Tin Bronze LTB2) not specified; body hydrostatic test pressure (2.1 MPa) omitted.',
    remedy: 'Mandate ISI marked landing valves manufactured from Grade LTB-2 gunmetal under IS 5290 Clause 4.',
    spec: '63mm single outlet oblique type landing valves manufactured from gunmetal conforming to IS 5290 with instantaneous female outlet, stainless steel spindle, blank cap, and 15m Type A synthetic fire hose.'
  },
  {
    name: 'Standalone Solar LED Street Lighting Systems with LiFePO4 Battery',
    category: 'Renewable Energy',
    quantity: '1,500 Units',
    file: 'CPWD-SOLAR-2026-23-SOLAR-STREETLIGHTS.pdf',
    std: 'IS 16107 (Part 2/Sec 1): 2012',
    stdTitle: 'Luminaires Performance - LED Luminaires',
    edition: '1st Revision',
    secondary: 'IS 16046 (Part 2): 2018',
    secondaryTitle: 'Secondary Cells and Batteries Containing Alkaline or Other Non-Acid Electrolytes (Lithium)',
    testing: 'IS 10322 (Part 5/Sec 3)',
    testingTitle: 'Road and Street Luminaires Specification',
    qco: 'MNRE Specification for Solar Street Lighting & BIS CRS Registration',
    gap: 'Battery cycle life (> 2000 cycles at 80% DOD) and autonomous operating days during monsoon not defined.',
    remedy: 'Incorporate Lithium Ferro Phosphate (LiFePO4) battery compliance under IS 16046 Part 2 with 3 days autonomy.',
    spec: 'Standalone 30W LED solar street lighting system with 100Wp MNRE approved PV module, 12.8V 36Ah LiFePO4 battery pack, MPPT dusk-to-dawn charge controller, and galvanized octagonal 6m pole.'
  },
  {
    name: 'Heavy Duty Non-Clog Submersible Sewage Pumpsets 15 kW',
    category: 'Pumping Machinery',
    quantity: '12 Pumpsets',
    file: 'CPWD-PUMP-2026-24-SEWAGE-PUMPS.pdf',
    std: 'IS 14536: 1998 (Reaffirmed 2020)',
    stdTitle: 'Submersible Pumpsets for Sewage Applications - Specification',
    edition: '1st Revision',
    secondary: 'IS 9220: 1979',
    secondaryTitle: 'Pumps - Submersible Pumpsets for Clear, Cold, Fresh Water',
    testing: 'IS 5120: 1977',
    testingTitle: 'Technical Requirements for Rotodynamic Special Purpose Pumps',
    qco: 'BEE Mandatory Star Labeling for Agricultural/Industrial Pumps',
    gap: 'Solid sphere spherical clearance passing capacity and mechanical seal face material not specified.',
    remedy: 'Enforce minimum 75mm spherical solid handling capacity and dual silicon carbide mechanical seals under IS 14536.',
    spec: '15 kW, 415V, 3-phase, 50 Hz non-clog submersible sewage pump with single-vane channel impeller capable of passing 80mm solids, Class H insulation, IP68 protection, and automatic guide rail coupling system.'
  },
  {
    name: 'Fusion-Bonded Epoxy Coated Steel Rebars for Coastal PWD Structures',
    category: 'Corrosion Protection',
    quantity: '450 Metric Tonnes',
    file: 'CPWD-CIVIL-2026-25-EPOXY-REBARS.pdf',
    std: 'IS 13620: 1993 (Reaffirmed 2020)',
    stdTitle: 'Fusion Bonded Epoxy Coated Reinforcing Bars - Specification',
    edition: '1st Revision',
    secondary: 'IS 1786: 2008',
    secondaryTitle: 'High Strength Deformed Steel Bars for Concrete Reinforcement',
    testing: 'IS 1599: 2019',
    testingTitle: 'Metallic Materials - Bend Test',
    qco: 'Ministry of Steel Coastal Works Durability Directive',
    gap: 'Coating thickness uniformity (175 to 300 microns) and holiday test pinhole limits (max 2 per meter) omitted.',
    remedy: 'Enforce 100% in-line holiday testing at 67.5V and knife adhesion test verification strictly adhering to IS 13620.',
    spec: 'Fusion-bonded epoxy coating applied to high-strength deformed steel bars Fe 500D in accordance with IS 13620 with average dry film thickness of 250 microns and zero holidays for marine coastal RC structures.'
  },
  {
    name: 'Unplasticized Polyvinyl Chloride (uPVC) Multi-Chamber Windows',
    category: 'Building Openings',
    quantity: '4,500 Square Meters',
    file: 'CPWD-CIVIL-2026-26-UPVC-WINDOWS.pdf',
    std: 'IS 15087: 2001',
    stdTitle: 'Specification for Extruded Hollow Profiles of Unplasticized Polyvinyl Chloride (uPVC) for Windows and Doors',
    edition: '1st Revision',
    secondary: 'IS 2835: 1987',
    secondaryTitle: 'Flat Transparent Sheet Glass',
    testing: 'IS 15087 Annexure B',
    testingTitle: 'Impact Strength and Weathering Resistance of uPVC Profiles',
    qco: 'Green Rating for Integrated Habitat Assessment (GRIHA) Envelope Standards',
    gap: 'Wall thickness of main outer profile (< 2.2mm) fails structural wind load rating for upper floors.',
    remedy: 'Mandate Class A uPVC profiles with outer wall thickness >= 2.8mm and galvanized steel reinforcement (1.5mm) under IS 15087.',
    spec: 'Factory-glazed uPVC sliding and casement window assemblies conforming to IS 15087 Class A tropicalized lead-free profiles with 5mm toughened safety glass and multi-point security locking hardware.'
  },
  {
    name: 'Low-Voltage Fully Compartmentalized Motor Control Center (MCC)',
    category: 'Electrical Switchgear',
    quantity: '4 Switchboards',
    file: 'CPWD-ELEC-2026-27-MCC-PANEL.pdf',
    std: 'IS/IEC 61439 (Parts 1 & 2): 2011',
    stdTitle: 'Low-Voltage Switchgear and Controlgear Assemblies - Part 2: Power Switchgear and Controlgear Assemblies',
    edition: '1st Revision',
    secondary: 'IS 13947 (Parts 1-5)',
    secondaryTitle: 'Low-Voltage Switchgear and Controlgear',
    testing: 'IS 8623 (Superseded by IS/IEC 61439)',
    testingTitle: 'Specification for Low-Voltage Switchgear and Controlgear Assemblies',
    qco: 'DPIIT Low Voltage Switchgear (Quality Control) Order',
    gap: 'Tender cited withdrawn standard IS 8623 and omitted temperature rise test verification at 50 deg C ambient.',
    remedy: 'Amend tender to cite IS/IEC 61439-2 Form 4b separation with accredited design verification certificates.',
    spec: '415V, 50kA for 1s, Form 4b compartmentalized floor-standing motor control center with drawout motor starter feeders, copper busbars (rated 1.6A/sq.mm), microprocessor motor protection relays, and IP54 enclosure.'
  },
  {
    name: 'Resin-Bonded Mineral Rockwool Blankets for Thermal & Acoustic Insulation',
    category: 'Thermal Insulation',
    quantity: '18,000 Square Meters',
    file: 'CPWD-HVAC-2026-28-ROCKWOOL-INSULATION.pdf',
    std: 'IS 8183: 1993 (Reaffirmed 2020)',
    stdTitle: 'Bonded Mineral Wool - Specification',
    edition: '2nd Revision',
    secondary: 'IS 3144: 1992',
    secondaryTitle: 'Methods of Test for Mineral Wool Thermal Insulation Materials',
    testing: 'IS 3346: 1980',
    testingTitle: 'Method for the Determination of Thermal Conductivity of Thermal Insulation Materials',
    qco: 'BEE Energy Conservation Building Code (ECBC) Envelope Regulations',
    gap: 'Non-combustibility Class A1 rating and maximum thermal conductivity at mean temperature 50 deg C omitted.',
    remedy: 'Specify density 48 kg/m3, non-combustibility as per BS 476 Part 4, and thermal conductivity <= 0.033 W/m.K under IS 8183.',
    spec: 'Resin-bonded preformed Rockwool thermal insulation blankets conforming to IS 8183 with density 48 kg/m3, reinforced aluminium foil facing, and water repellent treatment for HVAC chilled air ducting.'
  },
  {
    name: 'Conductive Anti-Static Homogeneous Vinyl Flooring for ICU & Server Rooms',
    category: 'Hospital Finishing',
    quantity: '3,200 Square Meters',
    file: 'CPWD-HOSP-2026-29-ANTISTATIC-VINYL.pdf',
    std: 'IS 3462: 1986 (Reaffirmed 2020)',
    stdTitle: 'Specification for Flexible PVC Flooring',
    edition: '2nd Revision',
    secondary: 'IS 3461: 1980',
    secondaryTitle: 'PVC (Vinyl) Asbestos Floor Tiles',
    testing: 'IS 3464: 1986',
    testingTitle: 'Methods of Test for Plastic Flooring Materials',
    qco: 'National Accreditation Board for Hospitals (NABH) Operation Theatre Guidelines',
    gap: 'Electrical resistance range (10^4 to 10^6 Ohms) not verified; antibacterial fungistatic certification omitted.',
    remedy: 'Mandate electrical resistance strictly between 5 x 10^4 and 10^6 ohms as per IS 3462 and ISO 10874 wear group T.',
    spec: '2.0mm thick homogeneous conductive vinyl sheet flooring conforming to IS 3462 with conductive carbon black grid backing, polyurethane reinforcement (PUR), welded seams, and continuous copper strip earthing grid.'
  },
  {
    name: 'Cast Iron Double Flanged Sluice Valves Class PN 1.6',
    category: 'Waterworks Valves',
    quantity: '350 Valves (DN 80 to DN 300)',
    file: 'CPWD-WATER-2026-30-SLUICE-VALVES.pdf',
    std: 'IS 14846: 2000 (Reaffirmed 2021)',
    stdTitle: 'Sluice Valves for Water Works Purposes (50 to 1200 mm Size) - Specification',
    edition: '1st Revision',
    secondary: 'IS 778: 1984',
    secondaryTitle: 'Copper Alloy Gate, Globe and Check Valves for Water Works Purposes',
    testing: 'IS 1538: 1993',
    testingTitle: 'Cast Iron Fittings for Pressure Pipes for Water, Gas and Sewage',
    qco: 'DPIIT Valves (Quality Control) Order',
    gap: 'Seat test pressure (1.6 MPa) and body test pressure (2.4 MPa) inspection clause omitted from factory inspection.',
    remedy: 'Require mandatory ISI mark under IS 14846 with stainless steel stem (SS 410) and bronze trim (IS 318 LTB2).',
    spec: 'Cast Iron double-flanged resilient-seated sluice valves Class PN 1.6 conforming to IS 14846 with non-rising stainless steel spindle, EPDM encapsulated ductile iron wedge, and electrostatic powder epoxy coating.'
  },
  {
    name: 'Group B1a Fully Vitrified Ceramic Floor Tiles for Transit Terminals',
    category: 'Floor Finishes',
    quantity: '22,000 Square Meters',
    file: 'CPWD-CIVIL-2026-31-VITRIFIED-TILES.pdf',
    std: 'IS 15622: 2017',
    stdTitle: 'Pressed Ceramic Tiles - Specification (First Revision)',
    edition: '1st Revision',
    secondary: 'IS 13630 (Parts 1-15)',
    secondaryTitle: 'Ceramic Tiles - Methods of Test',
    testing: 'IS 15622 Group B1a Table 3',
    testingTitle: 'Water Absorption and Modulus of Rupture Requirements for Ceramic Tiles',
    qco: 'DPIIT Ceramic Tiles Quality Control Order',
    gap: 'Water absorption limit cited as <= 0.5% but Mohs surface hardness (> 7) and anti-skid pendulum test omitted.',
    remedy: 'Enforce Group B1a with water absorption <= 0.08%, breaking strength >= 1500 N, and slip resistance class R10.',
    spec: 'Heavy-duty double-charged unglazed fully vitrified floor tiles (size 600x600x10mm) conforming to IS 15622 Group B1a with modulus of rupture >= 38 N/mm2, scratch hardness >= 7 on Mohs scale, and rectified edges.'
  },
  {
    name: 'Maintenance-Free Chemical Earthing Copper-Bonded Steel Electrodes',
    category: 'Earthing & Lightning',
    quantity: '1,200 Sets',
    file: 'CPWD-ELEC-2026-32-CHEMICAL-EARTHING.pdf',
    std: 'IS 3043: 2018',
    stdTitle: 'Code of Practice for Earthing (First Revision)',
    edition: '2nd Revision',
    secondary: 'IS 1239 (Part 1): 2004',
    secondaryTitle: 'Steel Tubes for Electrical Applications',
    testing: 'IEC 62561-2',
    testingTitle: 'Lightning Protection System Components - Requirements for Earth Electrodes',
    qco: 'Central Electricity Authority (Safety Requirements) Standards',
    gap: 'Copper molecular bonding thickness (< 100 microns) inadequate for 25-year corrosive soil longevity.',
    remedy: 'Mandate minimum 250 microns 99.9% pure electrolytic copper molecular bonding compliant with IS 3043 & IEC 62561-2.',
    spec: 'Maintenance-free chemical earthing system comprising 3.0m long 17.2mm diameter copper-bonded steel rod with minimum 250 microns copper molecular bonding, UL listed, and 25 kg carbonaceous backfill compound.'
  }
];

export { PO_TOPICS };
console.log(`Loaded ${PO_TOPICS.length} Procurement Officer topics.`);
