// 32 PSU Topics (Heavy Electrical, Energy, Oil & Gas, Mining, Defence, Steel)
export const PSU_TOPICS = [
  {
    name: 'Cast Carbon Steel Gate Valves Class 600 for Hydrocarbon Service',
    category: 'Oil, Gas & Petrochemical',
    quantity: '180 Valves (4 inch to 24 inch)',
    file: 'IOCL-REFINERY-2026-01-GATE-VALVES-CL600.pdf',
    std: 'IS 14846: 2000 / API 600',
    stdTitle: 'Steel Gate Valves - Flanged and Butt-Welding Ends, Bolted Bonnets for Petroleum and Natural Gas Industries',
    edition: '1st Revision',
    secondary: 'IS 778: 1984',
    secondaryTitle: 'Valves for Industrial Applications',
    testing: 'API 598 / IS 6157',
    testingTitle: 'Valve Inspection and Testing Standards',
    qco: 'DPIIT Valves (Quality Control) Order / OISD Guidelines',
    gap: 'Fugitive emissions compliance (ISO 15848-1 Class AH) and NACE MR0175 sour service metallurgy not verified.',
    remedy: 'Mandate ASTM A216 Grade WCB with 13% Cr (Trim 8) and ISO 15848-1 low-fugitive graphite gland packing.',
    spec: 'ASME Class 600 flexible wedge gate valves manufactured from cast carbon steel ASTM A216 WCB with full stellite hardfaced seat rings, outside screw and yoke (OS&Y), bolted bonnet, and API 6FA fire-safe certification.'
  },
  {
    name: 'Seamless Cold-Drawn Alloy Steel Superheater Boiler Tubes',
    category: 'Thermal Power Generation',
    quantity: '4,500 Metric Tonnes',
    file: 'NTPC-SUPERCRITICAL-2026-02-BOILER-TUBES.pdf',
    std: 'IS 1914 (Parts 1-4): 1984',
    stdTitle: 'Carbon and Alloy Steel Boiler and Superheater Tubes for High Pressure Service',
    edition: '2nd Revision',
    secondary: 'IS 2825: 1969',
    secondaryTitle: 'Code for Unfired Pressure Vessels',
    testing: 'IBR 1950 (Indian Boiler Regulations)',
    testingTitle: 'Regulations for Boiler Materials and Welded Superheater Tubes',
    qco: 'Central Boilers Board (CBB) Statutory Inspecting Authority Form III-A',
    gap: 'Tender missing mandatory IBR Form III-A witness testing and 100% ultrasonic flaw examination schedule.',
    remedy: 'Enforce statutory Indian Boiler Regulations (IBR) Form III-A inspection and ASTM A213 Grade T91/T22 compliance.',
    spec: 'Seamless cold-drawn ferritic alloy steel boiler tubes Grade T91 (9% Cr, 1% Mo, V, Cb) conforming to IS 1914 / IBR 1950 for 660 MW supercritical steam generators at 593 deg C steam temperature and 250 bar pressure.'
  },
  {
    name: '765kV Double Circuit Heavy Loading Galvanized Transmission Towers',
    category: 'Power Grid Transmission',
    quantity: '12,500 Metric Tonnes Structural Steel',
    file: 'POWERGRID-765KV-2026-03-TRANSMISSION-TOWERS.pdf',
    std: 'IS 802 (Parts 1-3): 1995 / 2015',
    stdTitle: 'Use of Structural Steel in Overhead Transmission Line Towers - Code of Practice',
    edition: '3rd Revision',
    secondary: 'IS 2062: 2011',
    secondaryTitle: 'Hot Rolled Structural Steel',
    testing: 'IS 4759: 1996',
    testingTitle: 'Hot-Dip Zinc Coatings on Structural Steel',
    qco: 'Ministry of Power Technical Standards for Construction of Electrical Plants and Lines',
    gap: 'Broken-wire longitudinal containment load conditions and full-scale proto tower destructive testing missing.',
    remedy: 'Require full-scale proto tower destructive testing at accredited CPRI/SERC test bed as per IS 802 Part 3.',
    spec: 'Fabrication and galvanizing of 765kV double circuit transmission line towers using high-tensile steel angles Grade E350/E250 conforming to IS 2062 with minimum 610 g/m2 hot-dip zinc coating as per IS 4759.'
  },
  {
    name: 'Fire-Resistant Anti-Static Steel Cord Conveyor Belting 2000mm',
    category: 'Mining & Coal Beneficiation',
    quantity: '18,500 Meters Belting',
    file: 'COALINDIA-MINE-2026-04-STEEL-CORD-CONVEYOR.pdf',
    std: 'IS 1891 (Part 5): 1993 (Reaffirmed 2019)',
    stdTitle: 'Rubber Conveyor and Elevator Belting - Part 5: Steel Cord Conveyor Belting',
    edition: '2nd Revision',
    secondary: 'IS 15652: 2006',
    secondaryTitle: 'Insulating Mats for Electrical Purposes',
    testing: 'IS 1891 (Part 1): 1994',
    testingTitle: 'Determination of Fire Resistance and Electrical Surface Resistance',
    qco: 'Directorate General of Mines Safety (DGMS) Fire-Resistant Approval',
    gap: 'DGMS statutory flame propagation drum friction test certificate and electrical surface resistivity missing.',
    remedy: 'Mandate DGMS field trial approval and electrical surface resistance <= 3 x 10^8 ohms as per IS 1891 Part 1.',
    spec: '2000mm wide ST-2500 steel cord conveyor belt with fire-resistant anti-static (FRAS) synthetic rubber covers (8mm top x 6mm bottom), open-construction zinc-galvanized steel cords, and high dynamic adhesion.'
  },
  {
    name: 'Microprocessor-Based Electronic Interlocking (EI) Railway Signalling',
    category: 'Railway Signalling & Automation',
    quantity: '15 Station Systems',
    file: 'RAILTEL-SIGNALLING-2026-05-ELECTRONIC-INTERLOCKING.pdf',
    std: 'IRS S-24 / IS 13252 (Part 1)',
    stdTitle: 'Indian Railway Standard Specification for Electronic Interlocking Signalling System',
    edition: '2nd Revision',
    secondary: 'RDSO/SPN/192/2019',
    secondaryTitle: 'Electronic Interlocking Equipment for Railway Stations',
    testing: 'CENELEC EN 50126 / EN 50128 / EN 50129',
    testingTitle: 'Railway Applications - Safety Integrity Level 4 (SIL-4)',
    qco: 'Research Designs and Standards Organisation (RDSO) Approved Vendor Mandate',
    gap: 'Fail-safe 2-out-of-3 (2oo3) hardware architecture and SIL-4 functional safety third-party certificate omitted.',
    remedy: 'Enforce RDSO Type Approval specification RDSO/SPN/192/2019 with certified CENELEC SIL-4 safety integrity.',
    spec: 'Centralized microprocessor-based electronic interlocking system with warm-standby 2oo3 multi-processor architecture, optical fiber communication networking, solid-state event logging, and dual redundant power supply.'
  },
  {
    name: '33kV 3-Core Armoured Subsea Umbilical Power Cable for Offshore Platforms',
    category: 'Offshore Hydrocarbon & Marine',
    quantity: '28 Kilometers Subsea Cable',
    file: 'ONGC-OFFSHORE-2026-06-SUBSEA-UMBILICAL.pdf',
    std: 'IS 7098 (Part 3): 1993 / IEC 60502-2',
    stdTitle: 'Crosslinked Polyethylene Insulated Cables for Working Voltages from 66 kV up to and including 220 kV',
    edition: '1st Revision',
    secondary: 'IS 1554: 1988',
    secondaryTitle: 'PVC Insulated Electric Cables',
    testing: 'CIGRE Electra 171 / IEC 60840',
    testingTitle: 'Recommendations for Mechanical Testing of Submarine Cables',
    qco: 'Directorate General of Hydrocarbons (DGH) Offshore Safety Regulations',
    gap: 'Radial water-tightness lead sheath barrier and dynamic bending fatigue flexure test missing.',
    remedy: 'Mandate continuous extruded lead-alloy radial water barrier and heavy galvanized round steel wire double armour.',
    spec: '33kV (E), 3-Core x 240 sq.mm stranded circular copper conductor subsea power cable with dry-cured triple-extruded XLPE insulation, extruded metallic lead alloy sheath, integrated 24-core SM optical fibers, and double steel wire armour.'
  },
  {
    name: '250MW Francis Hydro Turbine Runner Forgings & CNC Machined Casings',
    category: 'Hydroelectric Power Generation',
    quantity: '2 Turbine Runners (250 MW each)',
    file: 'NHPC-HYDRO-2026-07-FRANCIS-TURBINE.pdf',
    std: 'IS 3943: 1996 (Reaffirmed 2021)',
    stdTitle: 'Code of Practice for Testing of Hydraulic Turbines Surface',
    edition: '2nd Revision',
    secondary: 'IS 2062: 2011',
    secondaryTitle: 'Structural Steel Standards',
    testing: 'IEC 60193 / ASTM A743',
    testingTitle: 'Hydraulic Turbines, Storage Pumps and Pump-Turbines - Model Acceptance Tests',
    qco: 'Central Electricity Authority Hydro Plant Technical Standards',
    gap: 'Cavitation erosion resistance stainless steel grade (13% Cr, 4% Ni martensitic) chemical limits missing.',
    remedy: 'Mandate monolithic single-piece forged/cast stainless steel Grade CA6NM (13Cr-4Ni) as per ASTM A743.',
    spec: '250MW high-head Francis hydro turbine runner designed for 340m rated head fabricated from vacuum degassed 13Cr-4Ni martensitic stainless steel with 5-axis CNC machined blade profiles and 100% volumetric ultrasonic inspection.'
  },
  {
    name: '400kV Sulphur Hexafluoride (SF6) Gas Insulated Substation Switchgear',
    category: 'High-Voltage Switchgear',
    quantity: '14 GIS Bays (400kV)',
    file: 'POWERGRID-400KV-2026-08-GIS-SWITCHGEAR.pdf',
    std: 'IS/IEC 62271-203: 2011',
    stdTitle: 'High-Voltage Switchgear and Controlgear - Part 203: Gas-Insulated Metal-Enclosed Switchgear for Rated Voltages Above 52 kV',
    edition: '1st Revision',
    secondary: 'IS 13118: 1991',
    secondaryTitle: 'Circuit Breakers Specification',
    testing: 'IS/IEC 62271-1: 2007',
    testingTitle: 'Common Specifications for High-Voltage Switchgear Standards',
    qco: 'Central Electricity Authority Grid Standards Regulations',
    gap: 'SF6 gas leakage rate threshold (<= 0.5% per annum) and partial discharge UHF online monitoring missing.',
    remedy: 'Enforce maximum SF6 leakage <= 0.1% per year per compartment and integrated UHF partial discharge sensors.',
    spec: '400kV, 4000A, 63kA for 1-second SF6 gas-insulated metal-enclosed switchgear with single-phase encapsulated busbars, spring-operated circuit breakers, motorized disconnectors, and dual-redundant digital density monitors.'
  },
  {
    name: '2500 kVA Heavy Marine Auxiliary Diesel Generator Sets 415V',
    category: 'Shipbuilding & Marine Defense',
    quantity: '6 Marine Gensets',
    file: 'MDL-SHIP-2026-09-MARINE-GENSETS.pdf',
    std: 'IS 10000 (Parts 1-12): 1980',
    stdTitle: 'Methods of Test for Internal Combustion Engines',
    edition: '1st Revision',
    secondary: 'IS 13364 (Parts 1 & 2): 1992',
    secondaryTitle: 'A.C. Generators Driven by Reciprocating Internal Combustion Engines',
    testing: 'IRS Rules for Construction of Steel Ships / IMO Tier II',
    testingTitle: 'Indian Register of Shipping (IRS) Marine Classification Rules',
    qco: 'Ministry of Defense Quality Assurance (DGQA) Clearance',
    gap: 'Tender missing Indian Register of Shipping (IRS) classification society witness test and NOx emission limits.',
    remedy: 'Mandate IRS Marine Class Type Approval with IMO MARPOL Annex VI Tier II compliance under IS 10000.',
    spec: '2500 kVA, 415V, 3-phase, 50 Hz, 1000 RPM continuous heavy-duty marine auxiliary diesel generator sets with turbocharger, resilient anti-vibration mountings, duplex lube-oil filters, and IRS marine certification.'
  },
  {
    name: 'API 5L Grade X70 PSL2 Submerged Arc Welded (SAWL) Gas Line Pipe',
    category: 'Cross-Country Gas Transmission',
    quantity: '140 Kilometers (30 inch OD)',
    file: 'GAIL-GASGRID-2026-10-X70-SAWL-PIPES.pdf',
    std: 'IS 3589: 2001 / API 5L (46th Edition)',
    stdTitle: 'Steel Pipes for Water and Sewage (168.3 to 2540 mm Outside Diameter) / API Spec 5L Specification for Line Pipe',
    edition: '3rd Revision',
    secondary: 'IS 2062: 2011',
    secondaryTitle: 'Structural Steel Standards',
    testing: 'NACE TM0284 / NACE TM0177',
    testingTitle: 'Hydrogen-Induced Cracking (HIC) and Sulfide Stress Corrosion Cracking (SSCC) Tests',
    qco: 'PNGRB Technical Standards and Specifications for Natural Gas Pipelines',
    gap: 'Drop Weight Tear Test (DWTT >= 85% shear area at -10 deg C) and sour service HIC testing omitted.',
    remedy: 'Mandate API 5L PSL2 Annex H sour service compliance with 3-layer polyethylene (3LPE) external anti-corrosion coating.',
    spec: '30-inch outside diameter (762mm), 14.3mm wall thickness longitudinal submerged arc welded (SAWL) line pipe Grade X70MS PSL2 manufactured from vacuum-degassed inclusion-controlled thermomechanical rolled plate.'
  },
  {
    name: '150/30-Tonne Double Girder Heavy Duty EOT Steel Mill Cranes',
    category: 'Heavy Material Handling',
    quantity: '4 Heavy EOT Cranes',
    file: 'SAIL-STEEL-2026-11-EOT-CRANES-150T.pdf',
    std: 'IS 3177: 1999 (Reaffirmed 2019)',
    stdTitle: 'Code of Practice for Electric Overhead Travelling Cranes and Gantry Cranes Other Than Steel Works Cranes',
    edition: '2nd Revision',
    secondary: 'IS 4137: 1985 (Reaffirmed 2020)',
    secondaryTitle: 'Code of Practice for Heavy Duty Electric Overhead Travelling Cranes Including Special Service Cranes for Steel Works',
    testing: 'IS 807: 2006',
    testingTitle: 'Design, Erection and Testing of Structural Portion of Cranes and Hoists',
    qco: 'DPIIT Heavy Machinery Safety Directive',
    gap: 'Tender incorrectly cited commercial crane code IS 3177 instead of statutory steel plant mill crane standard IS 4137 Class M8.',
    remedy: 'Re-align tender to IS 4137 Class M8 / Class 4 extra heavy duty duty-cycle with forged alloy hooks (IS 15560).',
    spec: '150-tonne main hoist / 30-tonne auxiliary hoist double-girder steel mill crane (span 28m) compliant with IS 4137 Class M8 with dual AC variable frequency motor drives, forged alloy steel ramshorn hook, and air-conditioned operator cabin.'
  },
  {
    name: 'Heavy Water Reactor Primary Heat Transport Seamless Austenitic Piping',
    category: 'Nuclear Power Generation',
    quantity: '2,800 Meters Nuclear Piping',
    file: 'NPCIL-NUCLEAR-2026-12-PRIMARY-HEAT-PIPES.pdf',
    std: 'IS 2825: 1969 (Reaffirmed 2018)',
    stdTitle: 'Code for Unfired Pressure Vessels',
    edition: '1st Revision',
    secondary: 'IS 1239 (Part 1): 2004',
    secondaryTitle: 'Steel Tubes for Pressure Applications',
    testing: 'ASME Section III Division 1 Subsection NB',
    testingTitle: 'Rules for Construction of Nuclear Facility Components - Class 1 Piping',
    qco: 'Atomic Energy Regulatory Board (AERB) Safety Code for Nuclear Power Plant Design',
    gap: 'Cobalt trace impurity limit (<= 0.05% Co to prevent radioactive activation) not specified.',
    remedy: 'Mandate strict Cobalt chemistry <= 0.03% and 100% volumetric radiographic & ultrasonic testing under AERB/SC/D.',
    spec: 'Seamless cold-finished austenitic stainless steel piping (DN 300mm Sch 80) manufactured from vacuum-induction melted Grade 304LN conforming to ASME Section III Class 1 with strict restricted cobalt content for 700 MWe PHWR.'
  },
  {
    name: 'Sacrificial Aluminium Alloy Anodes for Offshore Platform Jackets',
    category: 'Cathodic Corrosion Protection',
    quantity: '1,200 Anodes (250 kg each)',
    file: 'ONGC-OFFSHORE-2026-13-SACRIFICIAL-ANODES.pdf',
    std: 'IS 8587: 1997 (Reaffirmed 2020)',
    stdTitle: 'Aluminium Alloy Anodes for Cathodic Protection - Specification',
    edition: '1st Revision',
    secondary: 'IS 8062 (Parts 1-3)',
    secondaryTitle: 'Code of Practice for Cathodic Protection of Steel Structures',
    testing: 'DNV RP-B401 / NACE TM0190',
    testingTitle: 'Cathodic Protection Design and Electrochemical Efficiency Testing of Aluminium Anodes',
    qco: 'Offshore Safety Regulations (DGH Guidelines)',
    gap: 'Electrochemical capacity rating (minimum 2500 A-h/kg) and closed-circuit potential not verified.',
    remedy: 'Mandate DNV RP-B401 electrochemical test certificates and Indium-Zinc alloy chemistry compliant with IS 8587.',
    spec: 'Cast sacrificial aluminium-indium-zinc alloy stand-off anodes (net weight 250 kg) with tubular steel core insert, achieving minimum electrochemical capacity 2600 A.h/kg and closed-circuit potential -1050 mV vs Ag/AgCl.'
  },
  {
    name: 'High-Chrome Alloy Abrasion-Resistant Heavy Slurry Pumps 350 kW',
    category: 'Thermal Power Auxiliary Machinery',
    quantity: '8 Slurry Pumpsets',
    file: 'NTPC-ASH-2026-14-SLURRY-PUMPS.pdf',
    std: 'IS 14536: 1998',
    stdTitle: 'Submersible Pumpsets for Sewage and Slurry Applications',
    edition: '1st Revision',
    secondary: 'IS 5120: 1977',
    secondaryTitle: 'Technical Requirements for Rotodynamic Special Purpose Pumps',
    testing: 'IS 9137: 1979',
    testingTitle: 'Code for Acceptance Tests for Centrifugal, Mixed Flow and Axial Pumps - Class C',
    qco: 'DPIIT Heavy Pumps Technical Directives',
    gap: 'Wet-end impeller casing metallurgy hardness (minimum 650 BHN high-chrome cast iron) omitted.',
    remedy: 'Enforce high-chromium alloy white iron ASTM A532 Class III Type A (27% Cr) with minimum 60 HRC hardness.',
    spec: 'Heavy-duty horizontal end-suction centrifugal ash slurry disposal pumps (capacity 1200 m3/hr @ 60m head) powered by 350 kW motor with replaceable high-chrome alloy liners, dynamic expeller seal, and grease-lubricated bearings.'
  },
  {
    name: 'Heavy Clad Reactor Pressure Vessels for Refinery Hydrocracking Units',
    category: 'Petroleum Refining Equipment',
    quantity: '2 Reactor Vessels (Weight 450T each)',
    file: 'BPCL-REFINERY-2026-15-REACTOR-VESSELS.pdf',
    std: 'IS 2825: 1969 (Class 1 Pressure Vessels)',
    stdTitle: 'Code for Unfired Pressure Vessels',
    edition: '1st Revision',
    secondary: 'IS 2062: 2011',
    secondaryTitle: 'Structural Steel Standards',
    testing: 'ASME Boiler and Pressure Vessel Code Section VIII Division 2',
    testingTitle: 'Alternative Rules for Construction of High-Pressure Vessels',
    qco: 'Petroleum and Explosives Safety Organization (PESO) Static & Mobile Pressure Vessels Rules',
    gap: 'Step-cooling temper embrittlement test protocol (Bruscato factor X <= 15 ppm) omitted in fabrication schedule.',
    remedy: 'Mandate 2.25Cr-1Mo-0.25V vanadium-modified alloy steel plate with explosion-bonded SS 347 weld overlay cladding.',
    spec: 'Hydrocracker reactor pressure vessels operating at 170 bar design pressure and 450 deg C design temperature fabricated from 150mm thick 2.25Cr-1Mo-V steel with 4mm internal stainless steel weld overlay conforming to ASME Sec VIII Div 2.'
  },
  {
    name: '400kV Silicone Composite Polymer Suspension Long-Rod Insulators',
    category: 'High-Voltage Transmission',
    quantity: '25,000 Insulator Strings',
    file: 'POWERGRID-400KV-2026-16-POLYMER-INSULATORS.pdf',
    std: 'IS 15451: 2004 / IEC 61109',
    stdTitle: 'Composite Insulators for A.C. Overhead Lines with a Nominal Voltage Greater than 1000 V',
    edition: '1st Revision',
    secondary: 'IS 1445: 1977',
    secondaryTitle: 'Porcelain Insulators for Overhead Power Lines',
    testing: 'IS 2071 (Parts 1-3)',
    testingTitle: 'High-Voltage Test Techniques',
    qco: 'Central Electricity Authority Technical Standards for Grid Transmission',
    gap: 'Tracking and erosion test (5000-hour multi-stress accelerated aging test) and corona ring design omitted.',
    remedy: 'Require 5000-hour multi-stress test certificate from accredited international/national laboratory and IS 15451 compliance.',
    spec: '400kV high-temperature vulcanized (HTV) silicone rubber composite long-rod insulators with 160 kN electro-mechanical failing load, high-purity boron-free E-CR glass fiber core, and forged steel hot-dip galvanized end-fittings.'
  },
  {
    name: 'Cryogenic Liquefied Natural Gas (LNG) Double-Wall Full Containment Storage Tanks',
    category: 'Cryogenic Hydrocarbons',
    quantity: '2 Full Containment Tanks (180,000 m3 each)',
    file: 'PETRONET-LNG-2026-17-CRYOGENIC-TANKS.pdf',
    std: 'IS 2825: 1969 / EN 14620 / API 620',
    stdTitle: 'Design and Manufacture of Site Built, Vertical, Cylindrical, Flat-Bottomed Steel Tanks for the Storage of Refrigerated, Liquefied Gases',
    edition: '1st Revision',
    secondary: 'IS 2062: 2011',
    secondaryTitle: 'Structural Steel Standards',
    testing: 'BS EN 14620-2 / API 620 Appendix Q',
    testingTitle: 'Cryogenic Materials Testing at -165 Degrees Celsius',
    qco: 'PESO Gas Cylinder & Cryogenic Pressure Vessel Technical Guidelines',
    gap: 'Inner primary container 9% Nickel steel Charpy V-notch impact lateral expansion test at -196 deg C omitted.',
    remedy: 'Mandate ASTM A841 / A553 Type I 9% Ni alloy steel with post-weld heat treatment and pre-stressed concrete outer tank.',
    spec: '180,000 cubic meter full containment cryogenic LNG storage tank with 9% nickel steel inner container designed for -165 deg C storage, expanded perlite insulation, and post-tensioned reinforced concrete outer barrier tank.'
  },
  {
    name: '3-Phase AC Asynchronous Traction Motors for 6000 HP Freight Electric Locomotives',
    category: 'Railway Traction Machinery',
    quantity: '240 Traction Motors',
    file: 'BHEL-TRACTION-2026-18-AC-TRACTION-MOTORS.pdf',
    std: 'IS 9670: 1980 / IEC 60349-2',
    stdTitle: 'Electric Traction - Rotating Electrical Machines for Rail and Road Vehicles',
    edition: '1st Revision',
    secondary: 'IS 13364: 1992',
    secondaryTitle: 'AC Generators Driven by Reciprocating Engines',
    testing: 'IEC 61377',
    testingTitle: 'Electric Traction - Combined Testing of Inverter and Motor',
    qco: 'RDSO Locomotive Directorate Specification MP.0.2400.43',
    gap: 'Class 200 high-temperature corona-resistant Kapton insulation and rotor copper-bar brazing fatigue test missing.',
    remedy: 'Enforce RDSO specification MP.0.2400.43 with vacuum pressure impregnated (VPI) Class 200 polyimide insulation.',
    spec: '1000 kW 3-phase axle-hung nose-suspended asynchronous induction traction motor operating from VVVF inverter with fabricated copper rotor cage, insulated hybrid ceramic ball bearings, and IP55 forced-air cooling.'
  },
  {
    name: 'Centrifugal Natural Gas Pipeline Booster Compressors with Dry Gas Seals',
    category: 'Oil & Gas Machinery',
    quantity: '4 Compressor Packages (18 MW each)',
    file: 'GAIL-GASGRID-2026-19-CENTRIFUGAL-COMPRESSOR.pdf',
    std: 'IS 13364: 1992 / API 617',
    stdTitle: 'Axial and Centrifugal Compressors and Expander-compressors for Petroleum, Chemical and Gas Industry Services',
    edition: '1st Revision',
    secondary: 'IS 3177: 1999',
    secondaryTitle: 'Heavy Machinery Overhead Cranes',
    testing: 'ASME PTC 10',
    testingTitle: 'Performance Test Code on Compressors and Exhausters',
    qco: 'PNGRB Gas Transmission Safety Regulations',
    gap: 'Full-load full-pressure hydrocarbon gas string test (PTC 10 Type 1) not specified in inspection plan.',
    remedy: 'Mandate ASME PTC 10 Type 1 witness test and tandem dry gas seals with nitrogen barrier purge under API 617.',
    spec: '18 MW gas turbine-driven multi-stage barrel type centrifugal gas booster compressor (discharge pressure 92 bar) with 17-4PH stainless steel impellers, active magnetic bearings, and digital anti-surge control system.'
  },
  {
    name: 'Urea Reactor High-Pressure Multi-Layered Ammonia Synthesis Vessel',
    category: 'Fertilizer & Chemical Process',
    quantity: '1 Synthesis Reactor (Weight 320T)',
    file: 'RCF-FERTILIZER-2026-20-UREA-REACTOR.pdf',
    std: 'IS 2825: 1969 (Class 1 Pressure Vessels)',
    stdTitle: 'Code for Unfired Pressure Vessels',
    edition: '1st Revision',
    secondary: 'IS 2062: 2011',
    secondaryTitle: 'Structural Steel Standards',
    testing: 'ASME Section VIII Division 1 & 2',
    testingTitle: 'Design and Fabrication of Layered High Pressure Vessels',
    qco: 'PESO Static Pressure Vessel Rules',
    gap: 'Huey nitric acid intergranular corrosion test (ASTM A262 Practice C) for urea grade SS 316L modified omitted.',
    remedy: 'Enforce Urea Grade 316L Modified (X2CrNiMo 18-14-3) metallurgy with max corrosion rate 0.6 mm/year under IS 2825.',
    spec: 'Multi-layer cylindrical high-pressure urea synthesis reactor (operating pressure 160 bar, temperature 195 deg C) with carbon steel multi-shrink layers and loose liner in urea-grade low-carbon stainless steel.'
  },
  {
    name: '220kV High-Pressure Fluid-Filled Underground XLPE Transmission Cable',
    category: 'EHV Power Transmission',
    quantity: '18 Kilometers EHV Cable',
    file: 'POWERGRID-220KV-2026-21-EHV-XLPE-CABLE.pdf',
    std: 'IS 7098 (Part 3): 1993 (Reaffirmed 2020)',
    stdTitle: 'Crosslinked Polyethylene Insulated Thermoplastic Sheathed Cables - For Working Voltages from 66 kV up to and including 220 kV',
    edition: '1st Revision',
    secondary: 'IS 10810 (Parts 1-64)',
    secondaryTitle: 'Methods of Test for Electric Cables',
    testing: 'IEC 62067',
    testingTitle: 'Power Cables with Extruded Insulation for Rated Voltages Above 150 kV up to 500 kV',
    qco: 'Central Electricity Authority (Technical Standards for Transmission) Regulations',
    gap: 'Tender missing mandatory 1-year pre-qualification test loop certificate (IEC 62067 Clause 13).',
    remedy: 'Mandate Type Test and Pre-Qualification (PQ) test certificate from KEMA/CPRI adhering to IS 7098 (Part 3).',
    spec: '220kV single-core 1000 sq.mm segmented Milliken copper conductor cable with super-clean cross-linked polyethylene insulation, corrugated seamless aluminium sheath, and extruded semi-conductive HDPE outer jacket.'
  },
  {
    name: 'Direct-Bonded Magnesite-Chrome Blast Furnace Refractory Bricks',
    category: 'Metallurgical Refractories',
    quantity: '1,500 Metric Tonnes Refractories',
    file: 'SAIL-STEEL-2026-22-REFRACTORY-BRICKS.pdf',
    std: 'IS 6: 2017',
    stdTitle: 'Refractories - Specification - Moderate Heat Duty Fireclay',
    edition: '5th Revision',
    secondary: 'IS 8: 1994',
    secondaryTitle: 'High Heat Duty Fireclay Refractories',
    testing: 'IS 1528 (Parts 1-20)',
    testingTitle: 'Methods of Sampling and Physical Tests for Refractory Materials',
    qco: 'DPIIT Refractories (Quality Control) Order',
    gap: 'Refractoriness Under Load (RUL ta >= 1700 deg C) and apparent porosity (<= 15%) unverified.',
    remedy: 'Mandate direct-bonded mag-chrome composition (MgO >= 60%, Cr2O3 >= 18%) with certified RUL testing as per IS 1528.',
    spec: 'Direct-bonded high-fired magnesite-chrome refractory bricks for blast furnace steel-making ladle slag line and torpedo cars with bulk density >= 3.10 g/cc, cold crushing strength >= 55 N/mm2, and hot modulus of rupture at 1400 deg C >= 8 N/mm2.'
  },
  {
    name: 'Flue Gas Desulphurization (FGD) Limestone Slurry Spray Header Pipes',
    category: 'Thermal Environmental Compliance',
    quantity: '12 Complete Header Assemblies',
    file: 'NTPC-FGD-2026-23-FGD-SPRAY-HEADERS.pdf',
    std: 'IS 1891: 1994',
    stdTitle: 'Abrasion Resistant Lining Standards',
    edition: '1st Revision',
    secondary: 'IS 9220: 1979',
    secondaryTitle: 'Slurry Handling Machinery',
    testing: 'ASTM D2996 / ISO 14692',
    testingTitle: 'Filament-Wound Reinforced Thermosetting Resin Pipe (FRP)',
    qco: 'Central Pollution Control Board (CPCB) SO2 Emission Norms for Thermal Plants',
    gap: 'Severe slurry erosion barrier (silicon carbide filled vinylester resin liner minimum 3mm) missing.',
    remedy: 'Mandate filament-wound vinyl ester glass-reinforced polymer (FRP) with wear-resistant SiC ceramic nozzles.',
    spec: 'Dual-laminate glass fiber reinforced vinyl ester resin (GRP/FRP) wet limestone slurry spray headers (DN 400mm) operating at 100 deg C in acidic wet scrubber environment conforming to ISO 14692 with solid silicon carbide whirl nozzles.'
  },
  {
    name: 'Armoured Electro-Optical Deep-Sea ROV Tether Cables 3000m',
    category: 'Deep Sea Mining & Ocean Exploration',
    quantity: '2 Tether Reels (3,000 meters each)',
    file: 'NIOT-DEEPSEA-2026-24-ROV-TETHER-CABLE.pdf',
    std: 'IS 1554 (Part 2): 1988',
    stdTitle: 'PVC Insulated (Heavy Duty) Electric Cables',
    edition: '2nd Revision',
    secondary: 'IS 9968 (Part 2): 2002',
    secondaryTitle: 'Elastomer Insulated Cables for Working Voltages Above 1100 V',
    testing: 'IEC 60794 / ISO 13628-5',
    testingTitle: 'Subsea Umbilicals and Dynamic Optical Cables',
    qco: 'Ministry of Earth Sciences Deep Ocean Mission Guidelines',
    gap: 'Hydrostatic pressure integrity at 300 bar (3000m ocean depth) and breaking load (minimum 180 kN) omitted.',
    remedy: 'Enforce high-tensile Aramid (Kevlar) synthetic fiber torque-balanced armour and hydrostatic pressure certification.',
    spec: '3000m neutrally buoyant electro-optical umbilical tether cable with 3x 4.0 sq.mm 3.3kV conductors, 12-core single-mode optical fiber tubes, water-blocked aramid fiber tensile yarn armour, and abrasion-resistant extruded polyurethane jacket.'
  },
  {
    name: 'High-Tensile Shipbuilding Structural Steel Plates Grade EH36',
    category: 'Defense Naval Architecture',
    quantity: '8,000 Metric Tonnes',
    file: 'COCHIN-SHIP-2026-25-EH36-STEEL-PLATES.pdf',
    std: 'IS 2062: 2011 / IS 3039: 1988',
    stdTitle: 'High Tensile Structural Steel / Steel Plates for Ship Building - Specification',
    edition: '3rd Revision',
    secondary: 'IS 1608: 2018',
    secondaryTitle: 'Metallic Materials Tensile Testing',
    testing: 'IRS Rules Part 2 / DNVGL-OS-B101',
    testingTitle: 'Rules for Classification of Naval Surface Ships - Hull Structures',
    qco: 'Ministry of Steel / Indian Register of Shipping (IRS) Marine Plate Directives',
    gap: 'Charpy V-notch impact energy verification at -40 deg C (minimum 34 Joules) omitted in mill test certificate.',
    remedy: 'Mandate Indian Register of Shipping (IRS) certified Grade EH36 thermomechanically rolled steel plate.',
    spec: 'Thermo-mechanically controlled processed (TMCP) high-strength hull structural steel plates Grade EH36 (thickness 12mm to 50mm) with minimum yield strength 355 MPa, through-thickness Z-axis ductility (Z35), and ultrasonic tested to Class 1.'
  },
  {
    name: 'Intrinsically Safe Digital Methane & Multi-Gas Telemetry Sensors for Mines',
    category: 'Underground Mining Safety',
    quantity: '350 Sensor Units',
    file: 'COALINDIA-SAFETY-2026-26-METHANE-SENSORS.pdf',
    std: 'IS/IEC 60079 (Part 11): 2011',
    stdTitle: 'Explosive Atmospheres - Part 11: Equipment Protection by Intrinsic Safety "i"',
    edition: '1st Revision',
    secondary: 'IS/IEC 60079 (Part 0): 2017',
    secondaryTitle: 'Explosive Atmospheres - General Requirements',
    testing: 'IS/IEC 60079-1',
    testingTitle: 'Equipment Protection by Flameproof Enclosures "d"',
    qco: 'Directorate General of Mines Safety (DGMS) Mandatory Intrinsic Safety Approval',
    gap: 'Missing DGMS Ex-ia approval certificate and infrared optical optical-chamber poison-resistance specification.',
    remedy: 'Mandate CIMFR testing and DGMS field safety license with non-depleting dual-beam infrared optical bench.',
    spec: 'Intrinsically safe Ex-ia digital underground coal mine methane and carbon monoxide continuous monitoring transmitter with dual-beam non-dispersive infrared (NDIR) optical bench, backlit LCD display, and 4-20mA/RS-485 Modbus telemetry.'
  },
  {
    name: 'Induced Draft Cooling Tower Fibre-Reinforced Polymer (FRP) Fan Blades',
    category: 'Power Plant Auxiliary Cooling',
    quantity: '32 Fan Blades Assemblies (Diameter 10m)',
    file: 'NTPC-POWER-2026-27-FRP-COOLING-FAN.pdf',
    std: 'IS 10000: 1980',
    stdTitle: 'General Requirements for Rotating Machinery',
    edition: '1st Revision',
    secondary: 'IS 3682: 1966',
    secondaryTitle: 'Specification for Industrial Fans and Blowers',
    testing: 'CTI STD-131 / ISO 1940-1',
    testingTitle: 'Cooling Technology Institute Fiberglass-Reinforced Plastic Fan Performance and Dynamic Balancing',
    qco: 'BEE Energy Efficiency Industrial Auxiliaries Guidelines',
    gap: 'Dynamic balance grade (ISO 1940-1 Grade G2.5) and leading-edge erosion protection tape missing.',
    remedy: 'Enforce Cooling Technology Institute (CTI) certified aerodynamics with 3M polyurethane erosion shield.',
    spec: '10-meter diameter 8-blade variable pitch aerofoil FRP cooling tower fans manufactured from epoxy vinyl ester resin with hollow construction, hot-dip galvanized steel hub, and dynamically balanced to ISO 1940 Grade G2.5.'
  },
  {
    name: '5-Axis Heavy CNC Gantry Milling Machine for Turbine Casings',
    category: 'High-Precision Machine Tools',
    quantity: '1 Turnkey CNC Machine',
    file: 'BHEL-MACHINING-2026-28-5AXIS-CNC-MILLING.pdf',
    std: 'IS 2161: 1962 / ISO 10791',
    stdTitle: 'Test Chart for Horizontal Surface Grinders and Machining Centers',
    edition: '1st Revision',
    secondary: 'IS 11000 (Part 1): 1984',
    secondaryTitle: 'Fire Safety of Machine Tool Facilities',
    testing: 'ISO 230-2',
    testingTitle: 'Determination of Accuracy and Repeatability of Positioning of Numerically Controlled Axes',
    qco: 'DPIIT Machine Tools (Quality Control) Order',
    gap: 'Volumetric geometric accuracy compensation and laser interferometer calibration protocol omitted.',
    remedy: 'Require VDI/DGQ 3441 / ISO 230-2 positional accuracy <= 0.008mm with Heidenhain glass optical scales.',
    spec: 'Heavy gantry-type 5-axis simultaneous CNC milling machining center (X=16m, Y=6m, Z=2.5m) with automatic universal milling head, 100 kW high-torque spindle, Siemens Sinumerik ONE CNC control, and Renishaw laser tool setter.'
  },
  {
    name: '400kV Heavy Duty Gapless Zinc Oxide Substation Surge Arresters',
    category: 'Substation Overvoltage Protection',
    quantity: '48 Surge Arresters',
    file: 'POWERGRID-400KV-2026-29-SURGE-ARRESTERS.pdf',
    std: 'IS 15086 (Part 4): 2014 / IEC 60099-4',
    stdTitle: 'Surge Arresters - Part 4: Metal-Oxide Surge Arresters without Gaps for A.C. Systems',
    edition: '1st Revision',
    secondary: 'IS 2071: 2016',
    secondaryTitle: 'High Voltage Testing Standards',
    testing: 'IS/IEC 60099-5',
    testingTitle: 'Surge Arresters - Selection and Application Recommendations',
    qco: 'Central Electricity Authority Technical Standards for Construction of Substations',
    gap: 'Repetitive charge transfer rating (Qrs >= 2.4 C) and pressure relief Class 63kA RMS omitted.',
    remedy: 'Mandate Class SM station heavy duty metal-oxide varistor blocks conforming strictly to IS 15086 (Part 4).',
    spec: '390kV rated, 10kA nominal discharge current gapless metal-oxide zinc surge arresters housed in silicone polymer housing with minimum creepage distance 13,000mm, line discharge Class 4, and digital surge monitor with leakage current meter.'
  },
  {
    name: 'Automated Rim-Seal Hydrocarbon Fire Foam Deluge Protection System',
    category: 'Petroleum Terminal Safety',
    quantity: '16 Crude Storage Tanks',
    file: 'IOCL-FIRE-2026-30-RIMSEAL-FOAM.pdf',
    std: 'IS 3844: 1989 (Reaffirmed 2020)',
    stdTitle: 'Code of Practice for Installation and Maintenance of Internal Fire Hydrants and Deluge Systems',
    edition: '1st Revision',
    secondary: 'OISD-STD-117',
    secondaryTitle: 'Fire Protection Facilities for Petroleum Depots, Terminals and Tank Farms',
    testing: 'NFPA 11 / EN 13565-2',
    testingTitle: 'Standard for Low-, Medium-, and High-Expansion Foam',
    qco: 'Oil Industry Safety Directorate (OISD) Mandatory Technical Standard',
    gap: 'Tender missing OISD-117 mandatory linear heat detection cable and pneumatic fast foam dump (< 30 seconds).',
    remedy: 'Mandate OISD-STD-117 Clause 6 compliance with UL-listed Aqueous Film Forming Foam (AFFF 3%) concentrate.',
    spec: 'Automatic rim-seal polyurethane foam pourer deluge fire suppression system for 79m diameter external floating roof crude oil storage tanks with linear heat sensor detection, pneumatic detection lines, and skid-mounted foam bladder tank.'
  },
  {
    name: 'High-Tensile Locked Coil Steel Wire Ropes for Mine Shaft Winding 48mm',
    category: 'Deep Mining Hoisting Systems',
    quantity: '8,000 Meters Wire Rope',
    file: 'HCL-MINING-2026-31-MINE-HOIST-ROPE.pdf',
    std: 'IS 2266: 2019',
    stdTitle: 'Steel Wire Ropes for General Engineering Purposes - Specification (Fifth Revision)',
    edition: '5th Revision',
    secondary: 'IS 1855: 2003',
    secondaryTitle: 'Stranded Steel Wire Ropes for Winding in Mines',
    testing: 'IS 6594: 2001',
    testingTitle: 'Technical Supply Conditions for Steel Wire Ropes and Test Methods',
    qco: 'Directorate General of Mines Safety (DGMS) Mine Hoist Statutory Regulations',
    gap: 'Tender cited general engineering standard IS 2266 instead of specialized mine winding rope standard IS 1855.',
    remedy: 'Update tender to mandate IS 1855 Full-Locked Coil construction with minimum breaking force 1,850 kN and DGMS approval.',
    spec: '48mm diameter full-locked coil galvanized steel wire rope for friction Koepe mine shaft hoist with interlocking Z-shaped outer wires, high-density non-rotating core, tensile grade 1770 N/mm2, conforming to IS 1855 and DGMS approved.'
  },
  {
    name: '50MWh Modular Grid-Scale Lithium Iron Phosphate Battery Energy Storage System (BESS)',
    category: 'Grid Energy Storage',
    quantity: '50 MWh / 25 MW BESS Plant',
    file: 'NTPC-RENEWABLE-2026-32-GRID-BESS-50MWH.pdf',
    std: 'IS 16046 (Part 2): 2018 / IEC 62619',
    stdTitle: 'Secondary Cells and Batteries Containing Alkaline - Safety Requirements for Secondary Lithium Cells',
    edition: '1st Revision',
    secondary: 'IS 16221: 2015',
    secondaryTitle: 'Safety Qualification of Power Conversion Systems',
    testing: 'UL 9540A / IEC 62933-5-2',
    testingTitle: 'Test Method for Evaluating Thermal Runaway Fire Propagation in Battery Energy Storage Systems',
    qco: 'Ministry of Power Guidelines for Procurement and Utilization of BESS',
    gap: 'UL 9540A unit-level and installation-level fire test report missing; deflagration explosion venting omitted.',
    remedy: 'Mandate UL 9540A thermal runaway report, NFPA 69 explosion prevention, and BIS CRS registration under IS 16046.',
    spec: '25 MW / 50 MWh utility grid-scale battery energy storage system comprising liquid-cooled IP55 containerized Lithium Iron Phosphate (LiFePO4) racks, bi-directional power conversion system (PCS), aerosol fire suppression, and SCADA interface.'
  }
];

console.log(`Loaded ${PSU_TOPICS.length} PSU topics.`);
